### ISSUE TITLE
Public .tiktoken files available?

### ISSUE THREAD

**Issue by Ontopic** [openai/tiktoken#10]
The files listed on https://github.com/openai/tiktoken/blob/main/tiktoken_ext/openai_public.py

f.e.
`az://openaipublic/gpt-2/encodings/main/encoder.json`
`az://openaipublic/gpt-2/encodings/main/vocab.bpe`
`az://openaipublic/encodings/cl100k_base.tiktoken`
`az://openaipublic/encodings/r50k_base.tiktoken`

Are these publically available somewhere? Not familiar with Azure cloud, ended up trying AzCopy, but yet no luck.

I'm starting to wonder if these files are actually public, since going through the repo, it seems they are loaded from local filesystem?

What is the recommended way to get these files?

_Really amazing work, and very happy to see it as an open-source contribution with excellent explanations throughout the comments in the code!_

**Comment by abdulbaseet-zahir** [comment]
Yes, files are public, you can see them like this, and they are accessed like this in the code.

```py
# pip install blobfile

import blobfile
import json

bpe_blobpath = "az://openaipublic/gpt-2/encodings/main/vocab.bpe"
json_blobpath = "az://openaipublic/gpt-2/encodings/main/encoder.json"

with blobfile.BlobFile(bpe_blobpath, "rb") as f:
    bpe_contents = f.read()

with blobfile.BlobFile(json_blobpath, "rb") as f:
    json_contents = json.loads(f.read())
```

**Comment by Ontopic** [comment]
🙏

As said, i believe this brings back some of the Open in OpenAI, in a way, that its "flagship" open-source product — gpt2-tokenizer — will see extended lifetime, and OpenAI, can continue to full the role as "generally accepted" BPE tokenizer.

Nice way to take your own throne, with such huge improvement.

Sure, you all are already following along, but what is the "way to go", about clearing up some stuff, like mentioned on https://brianlovin.com/hn/34008839

Are the issues here, somewhat ok place, to inform about the different tokenizers offered, or how should I go about acquiring more information about them?0

**Comment by hauntsaninja** [comment]
Yup, as abdulbaseet-zahir mentions, the files are public. I'm glad you find this useful :-)

In January, I'll add a way to map from tokenisers to engines available in the OpenAI API. This will make it clearer what a specific tokeniser should be used for.

Issues on this repo are a good place to ask additional questions, but I'm on vacation so you may not get answers until January.

**Comment by 1024er** [comment]
> Yes, files are public, you can see them like this, and they are accessed like this in the code.
> 
> ```python
> # pip install blobfile
> 
> import blobfile
> import json
> 
> bpe_blobpath = "az://openaipublic/gpt-2/encodings/main/vocab.bpe"
> json_blobpath = "az://openaipublic/gpt-2/encodings/main/encoder.json"
> 
> with blobfile.BlobFile(bpe_blobpath, "rb") as f:
>     bpe_contents = f.read()
> 
> with blobfile.BlobFile(json_blobpath, "rb") as f:
>     json_contents = json.loads(f.read())
> ```

get error: 

blobfile: error message=request failed with exception (<urllib3.connection.HTTPSConnection object at 0x7f243312a0a0>, 'Connection to login.microsoftonline.com timed out. (connect timeout=10)'), request=<Request method=POST url=https://login.microsoftonline.com/common/oauth2/v2.0/token params=None>, status=0, error=None, error_description=None, error_headers=None when executing http request <Request method=POST url=https://login.microsoftonline.com/common/oauth2/v2.0/token params=None> attempt 0, sleeping for 0.0 seconds before retrying
