### ISSUE TITLE
encoding.decode() function does not allow filtering out special tokens

### ISSUE THREAD

**Issue by sproocht** [openai/tiktoken#100]
Hi,
This is more a feature request to align to the Huggingface tokenizers while decoding model outputs. Could the parameter skip_special_tokens or similar be added to encoding.decode() function to filter out special tokens from the text output, for example while decoding predictions from the Whisper model?
Thanks!

**Comment by tbenst** [comment]
Temporary work around (feedback welcome):
```python
_re_special = re.compile(r"\<\|.+?\|\>")
def strip_special_tokens(string):
    return re.sub(_re_special, "", string)
```

**Comment by hauntsaninja** [comment]
A better workaround is probably something like `enc.decode([t for t in tokens if t not in enc._special_tokens])`. Note that this depends on a private attribute.

**Comment by hauntsaninja** [comment]
Closing as per my previous comment. This kind of manipulation is better done in user code
