### ISSUE TITLE
The tokenized results are not as expected when I added special tokens

### ISSUE THREAD

**Issue by tianxie-sf** [openai/tiktoken#102]
```
import tiktoken

gpt2_base = tiktoken.get_encoding("gpt2")


whitespaces = [" " * n for n in reversed(range(2, 32))]

special_tokens = dict()
idx = gpt2_base.n_vocab

for wsp in whitespaces:
    special_tokens[wsp] = idx
    idx += 1


enc = tiktoken.Encoding(
    name="gpt2_im",
    pat_str=gpt2_base._pat_str,
    mergeable_ranks=gpt2_base._mergeable_ranks,
    special_tokens={
        **gpt2_base._special_tokens,
        **special_tokens
    }
)

assert enc.n_vocab == gpt2_base.n_vocab + len(whitespaces)

text_1 = " " * 31
assert enc.decode([50257]) == text_1

print(enc.encode(text_1, allowed_special="all"))  # [50270, 50278, 50285]

```
I am trying to add special tokens for multiple whitespaces. However, it seems only some special tokens (2, 3, 6, 10, 18 whitespaces) can work when I encode a string.

For example, the expected encoding result for `" " * 31` is `[50257]`. However, the result is actually `[50270, 50278, 50285]`.

Am I doing something wrong? Thank you!

**Comment by hauntsaninja** [comment]
tiktoken doesn't provide any guarantees about what special tokens do if they overlap. Special tokens are usually used for things like `<|endoftext|>`. Why not add them as normal tokens?

**Comment by tianxie-sf** [comment]
> tiktoken doesn't provide any guarantees about what special tokens do if they overlap. Special tokens are usually used for things like `<|endoftext|>`. Why not add your spaces as normal tokens?

Thank you for your reply! Could you please provide an example of adding extra tokens as normal tokens? I didn't find examples in readme.

**Comment by hauntsaninja** [comment]
Choose your value for `mergeable_ranks`

**Comment by tianxie-sf** [comment]
> Choose your value for `mergeable_ranks`

Thank you so much! I adjusted my code.

```
import tiktoken

gpt2_base = tiktoken.get_encoding("gpt2")


whitespaces = [" " * n for n in reversed(range(2, 32))]

idx = gpt2_base.n_vocab

bpe_ranks = {}
for wsp in whitespaces:
    bpe_ranks[bytes(wsp, 'ascii')] = idx
    idx += 1

for k, v in gpt2_base._mergeable_ranks.items():
    bpe_ranks[k] = v


enc = tiktoken.Encoding(
    name="gpt2_im",
    pat_str=gpt2_base._pat_str,
    mergeable_ranks=bpe_ranks,
    special_tokens={
        **gpt2_base._special_tokens,
    }
)

assert enc.n_vocab == gpt2_base.n_vocab + len(whitespaces)

text_1 = " " * 4
assert enc.decode([50284]) == text_1

print(enc.encode(" " * 4 + "a"))  # [50285, 257] -> [" " * 3, " a"]
```
I want to get [50284, 64] ([" " * 4, "a"]) here. What else changes should I add?

**Comment by hauntsaninja** [comment]
Hmm if you do actually want your spaces to not get merged then yeah, you'll need special tokens that you control the overlapping behaviour for. There is no way to do this with tiktoken currently; if you fork you'll need to adjust the ordering here to respect some guarantee: https://github.com/openai/tiktoken/blob/46287bfa493f8ccca4d927386d7ea9cc20487525/src/lib.rs#L446

**Comment by hauntsaninja** [comment]
Actually, you could just use normal tokens and remove all tokens that start with a space from your vocabulary.

**Comment by tianxie-sf** [comment]
> Actually, you could just use normal tokens and remove all tokens that start with a space from your vocabulary.

Thank you so much! The current results look good to me. I don't need to actually get all of the spaces merged.
