### ISSUE TITLE
Create a tiktoken.max_tokens_for_model() function?

### ISSUE THREAD

**Issue by endolith** [openai/tiktoken#109]
Similar to the `tiktoken.encoding_for_model()` function, can we have a function to get the max_tokens for a particular model?   It doesn't seem like there is any other way to get this number programmatically, we have to search the website and find it in some random mention in the documentation.

**Comment by endolith** [comment]
and the ability to retrieve the cost per token.  If that's not appropriate for this library, then it should be in https://github.com/openai/openai-python

**Comment by hauntsaninja** [comment]
Thanks, I think both of these features would be great things for the OpenAI API to expose.

While I do work at OpenAI, I work on the research side of things, so it won't be me adding them to the OpenAI API and I'm not going to add this in tiktoken.
