### ISSUE TITLE
automatically adding special tokens

### ISSUE THREAD

**Issue by sangrok-lee-1021** [openai/tiktoken#11]
Thank you for really awesome code!
Should i add sos(start of sentence) or eos(end of sentence) by myself?

**Comment by hauntsaninja** [comment]
Yes, feel free to make your own custom encodings with your own custom special tokens.

You can pass whatever special tokens you want here when instantiating an Encoding object: https://github.com/openai/tiktoken/blob/40d9b1f14ef221fe040e0d6c3587375632328c25/tiktoken/core.py#L19
You can find example values for the other parameters here:
https://github.com/openai/tiktoken/blob/40d9b1f14ef221fe040e0d6c3587375632328c25/tiktoken_ext/openai_public.py#L15
