### ISSUE TITLE
Enhancing CJK Performance: Accelerating Training and Inference by 2-3 Times

### ISSUE THREAD

**Issue by golbin** [openai/tiktoken#111]
CJK languages, such as Chinese, Japanese, and Korean, require more tokens due to their extensive character sets. A single character is typically split into 2-3 tokens by the tokenizer.

However, these languages often use a single character to represent a word, as each character carries roughly the meaning of one word.

There are essential characters in CJK languages, which constitute a relatively small subset. Only 3,000 to 5,000 characters are needed for CJK representation. Therefore, **if Tiktoken includes only 10,000 to 15,000 characters**, the training and inference processes for **CJK languages could potentially become 2 to 3 times faster.**

--

Refine the sentences by GPT-4

**Comment by hauntsaninja** [comment]
Thanks, we're aware of this and take non English performance into account when designing our tokenisers :-) You'll notice for instance that you get significantly better compression on CJK text with cl100k_base than e.g. r50k_base
