### ISSUE TITLE
Is this not really similar to the tokenizer ChatGPT uses? (For counting tokens at least)

### ISSUE THREAD

**Issue by OneCodeToRuleThemAll** [openai/tiktoken#112]
I am inquiring because I use the web-based version of ChatGPT and utilize the tiktoken algorithm for tokenization. I have noticed that my input, including the initial system input message, amounts to approximately 3.6k tokens. Although the maximum context length is 4096 tokens, I am receiving an error indicating that my message is too long. I am confused as to why this is happening. Is there something I am overlooking?

It just hit me, is the API different from the browser version in the input text length as well?

**Comment by hauntsaninja** [comment]
tiktoken has the encodings ChatGPT uses. Maybe you're getting an error when your prompt + completion exceed context length.

If you need more help, try at one of these resources!
- [OpenAI community forum](https://community.openai.com/)
- [OpenAI discord](https://discord.com/invite/openai)
- Contact [support@openai.com](mailto:support@openai.com)
