### ISSUE TITLE
Get_encoding failures in aws lambda execution

### ISSUE THREAD

**Issue by jhb96** [openai/tiktoken#119]
Trying execute a lambda with tiktoken (0.0.3) makes timeouts when it tries to get_encoding. 
I though the cause was the threading in registry.py (`_lock = threading.RLock()`) but i tried to make threading in lambda and it worked for me.
I will continue looking for the problem...

**Comment by hauntsaninja** [comment]
Thanks, closing since there isn't a reproducible issue here
