### ISSUE TITLE
Invalid cross-device link error

### ISSUE THREAD

**Issue by MyIsaak** [openai/tiktoken#12]
I receive the following error:
```bash
Invalid cross-device link: '/tmp/tmpz830uswg/token.json' -> '/home/stromae/.blobfile/azure_access_tokens.json'
```

using
```python
def limit_to_3500_tokens(transcript):
        # limit transcript to 3500 tokens using tiktoken
        enc = tiktoken.get_encoding('gpt2')
        # loop until we find a transcript that is less than 3500 tokens
        limit = 0
        while True:
            transcript_head = transcript[:limit]
            if len(enc.encode(transcript_head)) > 3500:
                break
            limit += 100

        transcript_head = transcript[:limit]
        return transcript_head
```

**Comment by codedecde** [comment]
Are you using an NFS mount for  `/home/stromae` ? This might happen then (basically, blobFile cached a token and then is trying to create a link to on /tmp. But since the actual token itself is not on the same device, it causes an issue, I think).

You might be able to get around this issue by doing something like:

```[python]
import blobfile as bf
bf.configure(save_access_token_to_disk=False)

def limit_to_3500_tokens(transcript):
    ....

limit_to_3500_tokens()
```

**Comment by MyIsaak** [comment]
No, my file system is btrs and everything is mounted on root /. I'm using Fedora.

**Comment by hauntsaninja** [comment]
I've removed the use of blobfile for accessing public files in [tiktoken 0.1.2](https://github.com/openai/tiktoken/blob/main/CHANGELOG.md#v012). This should make your error go away.
