### ISSUE TITLE
The calculation results different with Tokenizer

### ISSUE THREAD

**Issue by mysaber** [openai/tiktoken#120]
Why are the calculation results different with  [Tokenizer](https://platform.openai.com/tokenizer)

**Comment by hauntsaninja** [comment]
Depends on what encoding you use.

**Comment by labdmitriy** [comment]
Hello @hauntsaninja,

Could you please explain in more details? I've noticed also this behavior, how to use tiktoken to reproduce exactly the same result as Tokenizer?

Thank you.

**Comment by eastack** [comment]
[How to count tokens with tiktoken](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) at "6. Counting tokens for chat API calls"

**Comment by labdmitriy** [comment]
@eastack Thank you!
I am familiar with it, I thought maybe it is something else 🙏
