### ISSUE TITLE
Azure blob is not accessible

### ISSUE THREAD

**Issue by amir-abdi** [openai/tiktoken#13]
```python
>>> import tiktoken
>>> tiktoken.get_encoding("gpt2")
```

Error:
```
blobfile._common.Error: Encountered an error when requesting an access token: `invalid_request: AADSTS900144: The request body must contain the following parameter: 'client_id'.
```

Stacktrace
```
>>> import tiktoken
>>> tiktoken.get_encoding("gpt2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/tiktoken/registry.py", line 61, in get_encoding
    enc = Encoding(**constructor())
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/tiktoken_ext/openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/tiktoken/load.py", line 58, in data_gym_to_mergeable_bpe_ranks
    vocab_bpe_contents = read_file_cached(vocab_bpe_file).decode()
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/tiktoken/load.py", line 30, in read_file_cached
    with blobfile.BlobFile(blobpath, "rb") as f:
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_ops.py", line 359, in BlobFile
    return default_context.BlobFile(
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_context.py", line 910, in BlobFile
    f = azure.StreamingReadFile(self._conf, path, size=file_size)
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 1015, in __init__
    st = maybe_stat(conf, path)
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 1280, in maybe_stat
    resp = execute_api_request(conf, req)
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 856, in execute_api_request
    return common.execute_request(conf, build_req)
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_common.py", line 504, in execute_request
    req = build_req()
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 853, in build_req
    req, auth=access_token_manager.get_token(conf, key=(account, container))
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_common.py", line 755, in get_token
    self._tokens[key], self._expirations[key] = self._get_token_fn(
  File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 726, in _get_access_token
    raise Error(
blobfile._common.Error: Encountered an error when requesting an access token: `invalid_request: AADSTS900144: The request body must contain the following parameter: 'client_id'.
Trace ID: 83948fe0-79a9-436b-ade1-c22eb4687000
Correlation ID: 84dc9ac6-fbf9-4c1c-87ee-56b866f2058c
Timestamp: 2022-12-20 18:59:07Z`.  You can attempt to fix this by re-running `az login`.
```

**Comment by hauntsaninja** [comment]
For now you should be able to fix by running `az login`, like the error says. Future versions of tiktoken will fix this.

**Comment by amir-abdi** [comment]
I'm logged in.  
Can you please double check if the blob is publicly accessible?

**Comment by gojira** [comment]
I have this issue as well even with `az login`.

It sounds like the container may not be publicly accessible?

**Comment by floodsung** [comment]
az logout works for me @gojira

**Comment by gojira** [comment]
@floodsung  🤣

**Comment by amir-abdi** [comment]
The issue has not yet been resolved, at least for me.
I've tried login into multiple tenants, as well as `az logout`. Same error:
`The request body must contain the following parameter: 'client_id'.`

**Comment by hauntsaninja** [comment]
I've removed the use of blobfile for accessing public files in [tiktoken 0.1.2](https://github.com/openai/tiktoken/blob/main/CHANGELOG.md#v012). This should make your error go away.

**Comment by gojira** [comment]
Thanks!

**Comment by Krystalklearkonnextions** [comment]
> ```python
> >>> import tiktoken
> >>> tiktoken.get_encoding("gpt2")
> ```
> 
> Error:
> ```
> blobfile._common.Error: Encountered an error when requesting an access token: `invalid_request: AADSTS900144: The request body must contain the following parameter: 'client_id'.
> ```
> 
> Stacktrace
> ```
> >>> import tiktoken
> >>> tiktoken.get_encoding("gpt2")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/tiktoken/registry.py", line 61, in get_encoding
>     enc = Encoding(**constructor())
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/tiktoken_ext/openai_public.py", line 11, in gpt2
>     mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/tiktoken/load.py", line 58, in data_gym_to_mergeable_bpe_ranks
>     vocab_bpe_contents = read_file_cached(vocab_bpe_file).decode()
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/tiktoken/load.py", line 30, in read_file_cached
>     with blobfile.BlobFile(blobpath, "rb") as f:
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_ops.py", line 359, in BlobFile
>     return default_context.BlobFile(
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_context.py", line 910, in BlobFile
>     f = azure.StreamingReadFile(self._conf, path, size=file_size)
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 1015, in __init__
>     st = maybe_stat(conf, path)
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 1280, in maybe_stat
>     resp = execute_api_request(conf, req)
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 856, in execute_api_request
>     return common.execute_request(conf, build_req)
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_common.py", line 504, in execute_request
>     req = build_req()
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 853, in build_req
>     req, auth=access_token_manager.get_token(conf, key=(account, container))
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_common.py", line 755, in get_token
>     self._tokens[key], self._expirations[key] = self._get_token_fn(
>   File "/home/miniconda3/envs/medeina/lib/python3.9/site-packages/blobfile/_azure.py", line 726, in _get_access_token
>     raise Error(
> blobfile._common.Error: Encountered an error when requesting an access token: `invalid_request: AADSTS900144: The request body must contain the following parameter: 'client_id'.
> Trace ID: 83948fe0-79a9-436b-ade1-c22eb4687000
> Correlation ID: 84dc9ac6-fbf9-4c1c-87ee-56b866f2058c
> Timestamp: 2022-12-20 18:59:07Z`.  You can attempt to fix this by re-running `az login`.
> ```

JavaScript Demo: Expressions - Unsigned right shift operator
1
const a = 5;          //  00000000000000000000000000000101
2
const b = 2;          //  00000000000000000000000000000010
3
const c = -5;         //  11111111111111111111111111111011
4
​
5
console.log(a >>> b); //  00000000000000000000000000000001
6
// expected output: 1
7
​
8
console.log(c >>> b); //  00111111111111111111111111111110
9
// expected output: 1073741822
10
​
Run ›
Reset

**Comment by hauntsaninja** [comment]
Use the latest released version of tiktoken
