### ISSUE TITLE
Cost for failed GPT requests

### ISSUE THREAD

**Issue by krishna-cactus** [openai/tiktoken#140]
Request to Chat models (gpt-3.5-turbo or gpt-4) can fail in 2 different ways:

Issue from OpenAI side - This is case where model is overloaded with other requests

Client adding a request time out - Here, for example, I as customer make a call with request time out as 10 seconds. The moment 10 seconds are passed, request is failed.

So in both situations, am I charged?

**Comment by hauntsaninja** [comment]
This isn't the appropriate venue for this kind of question, try the following resources:

- [OpenAI documentation](https://platform.openai.com/docs/introduction)
- [OpenAI community forum](https://community.openai.com/)
- [OpenAI discord](https://discord.com/invite/openai)
- Contact [support@openai.com](mailto:support@openai.com)
