### ISSUE TITLE
request error

### ISSUE THREAD

**Issue by floodsung** [openai/tiktoken#16]
blobfile: error message=request failed with exception HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Read timed out. (read timeout=10), request=<Request method=POST url=https://login.microsoftonline.com/common/oauth2/v2.0/token params=None>, status=0, error=None, error_description=None, error_headers=None when executing http request <Request method=POST url=https://login.microsoftonline.com/common/oauth2/v2.0/token params=None> attempt 1, sleeping for 0.1 seconds before retrying

how to solve it?

**Comment by 1024er** [comment]
> blobfile: error message=request failed with exception HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Read timed out. (read timeout=10), request=, status=0, error=None, error_description=None, error_headers=None when executing http request attempt 1, sleeping for 0.1 seconds before retrying
> 
> how to solve it?

I encountered the same problem, did you solve it? @floodsung

**Comment by hauntsaninja** [comment]
I've removed the use of blobfile for accessing public files in [tiktoken 0.1.2](https://github.com/openai/tiktoken/blob/main/CHANGELOG.md#v012). This should make your error go away.
