### ISSUE TITLE
Calculate token consumption for OpenAI function definitions

### ISSUE THREAD

**Issue by Pwuts** [openai/tiktoken#160]
* On 13 June, OpenAI introduced their new function calling API<sup>[1]</sup>
* These functions are inserted into the prompt in a non-trivial format<sup>[2]</sup>
* Neither `openai-python` nor `tiktoken` currently provide a function to calculate the expected token consumption of a set of function definitions

[1]: https://openai.com/blog/function-calling-and-other-api-updates
[2]: https://community.openai.com/t/how-to-calculate-the-tokens-when-using-function-call/266573/6

**Comment by hauntsaninja** [comment]
This is out of scope for tiktoken, maybe file an issue on openai-python
