### ISSUE TITLE
Deprecation of older models

### ISSUE THREAD

**Issue by AlexanderMorou** [openai/tiktoken#166]
On OpenAI's website, they recently released information about the [deprecation of older models in the Completions API](https://openai.com/blog/gpt-4-api-general-availability#deprecation-of-older-models-in-the-completions-api).

Is there any word on when we can see the new model -> encodings available in the source?

Are all of the replacements going to map to the `cl100k_base`?

I'm trying to keep my [implementation in C#](https://github.com/AlexanderMorou/BpeChatAI/blob/2b11a7bce25ca0ab2429a3effcb48ea6e12e8719/Libraries/BpeTokenizer/BytePairEncodingModels.cs) up to date.

**Comment by hauntsaninja** [comment]
cc @ted-at-openai would you help me stay on top of this? :-)

**Comment by ted-at-openai** [comment]
Yes, when the new models come out, we'll update tiktoken. They'll all use `cl100k_base`, so you can add support ahead of time if you like.

**Comment by AlexanderMorou** [comment]
> ... They'll all use `cl100k_base`, so you can add support ahead of time if you like.

Thanks, I'll do just that in my own mappings.
