### ISSUE TITLE
I added words from other languages, similar to Chinese, which caused the segmentation to fail properly, even though the word was in the vocabulary, the word was still split into multiple bytes in a sentence

### ISSUE THREAD

**Issue by FastBCSD** [openai/tiktoken#174]
![image](https://github.com/openai/tiktoken/assets/50363920/f129a244-7194-47a4-a8e3-5c75c1f99a6c)

**Comment by FastBCSD** [comment]
Too sad, make a day, finally write to support Chinese pat_str plus bit encoding successfully added Chinese ，，，， but can not normal word segmentation

**Comment by FastBCSD** [comment]
这是我的正则"'s|'t|'re|'ve|'m|'ll|'d| ?[\\p{L}\\p{Han}]+| ?\\p{N}+| ?[^\\s\\p{L}\\p{N}]+|\\s+(?!\\S)|\\s+"

**Comment by FastBCSD** [comment]
"'s|'t|'re|'ve|'m|'ll|'d| ?[\\p{L}\\p{Han}]+| ?\\p{N}+| ?[^\\s\\p{L}\\p{N}]+|\\s+(?!\\S)|\\s+"

**Comment by hauntsaninja** [comment]
This is expected behaviour from BPE; some merges are higher priority than others. See also https://github.com/openai/tiktoken/blob/main/tiktoken/_educational.py as a resource to help with questions about BPE. Also note that pasting text is much more effective than pasting screenshots.
