### ISSUE TITLE
TikToken.EncodingForModel("gpt-3.5-turbo") hangs when context is a WPF appplication.

### ISSUE THREAD

**Issue by felipedrumond** [openai/tiktoken#175]
I have a WPF C# application that uses
` TikToken tikToken = TikToken.EncodingForModel("gpt-3.5-turbo")`;
and will hand, even after getting a 200 http status when fetching 
https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken 

Using my same library in a Console context doesn't hang. 
1) what can be happening in the WPF context?
2) is there a way to bypass the download of cl100k_base.tiktoken all the time?

**Comment by hauntsaninja** [comment]
I don't know what WPF is and this library is not C#. Maybe you're using some unofficial fork?

**Comment by felipedrumond** [comment]
Sorry - this was supposed to be in TiktokenSharp (C#) nuget package.
