### ISSUE TITLE
Hugging Face tokenizers

### ISSUE THREAD

**Issue by denisyarats** [openai/tiktoken#18]
Hi, what is the best way to port tokenizers (e.g. vocabs) from Hugging Face and use them within tiktoken ? For example T5 tokenizer.

**Comment by hauntsaninja** [comment]
I think T5 used SentencePiece, and that huggingface just has a thin wrapper over https://github.com/google/sentencepiece/tree/master/python. tiktoken only supports BPE encodings.

Closing the issue, but feel free to follow up!

**Comment by Cppowboy** [comment]
How to use other bpe tokenizers from huggingface?

**Comment by cabbagetalk** [comment]
如何使用 Huggingface 中的其他 BPE 分词器？例如，编码 llama tokenizer 或 llama2 tokenizer。

**Comment by hauntsaninja** [comment]
You should be able to get something like https://github.com/openai/tiktoken/issues/60#issuecomment-1499977960 to work
