### ISSUE TITLE
Unable to install tiktoken in ubuntu 18.04 server

### ISSUE THREAD

**Issue by nagendra-rqsr** [openai/tiktoken#201]
I'm unable to install tiktoken python library  in Ubuntu server for django via pip install tiktoken.
It worked in local windows system but failing in the Ubuntu server
Below is whay it says after: pip install tiktoken

ERROR: Could not find a version that satisfies the requirement tiktoken (from versions: none)
ERROR: No matching distribution found for tiktoken

**Comment by hauntsaninja** [comment]
This isn't sufficient detail in this issue report for me to know for sure what's wrong, but my guess is you're using an old version of Python. tiktoken only supports Python 3.8 and newer.

**Comment by nagendra-rqsr** [comment]
Yeah, you are right, its Python 3.6.9
