### ISSUE TITLE
Nuitka compiler, unknown encoding "ck100_base"

### ISSUE THREAD

**Issue by aspoofer0224** [openai/tiktoken#207]
enabled_plugin option:[] is empty and couldnt load the encoding model and so far i couldnt find a solution to it, i've tried importing tiktoken_ext as a package in command but it didnt work like pyinstaller case. Highly appreciate if someone had succeed in building tiktoken with nuitka.

**Comment by hauntsaninja** [comment]
See the FAQ for pyinstaller, I assume you'll need to do something similar https://github.com/openai/tiktoken/issues/98
