### ISSUE TITLE
tiktoken does not work with blobfile==2.1.0

### ISSUE THREAD

**Issue by Praful932** [openai/tiktoken#209]
Produces errors when these commands are run
```
tiktoken.encoding_for_model("gpt-3.5-turbo") - ValueError: Unknown encoding cl100k_base
tiktoken.encoding_for_model("gpt-3.5-turbo-0613") - 'ABCMeta' object is not subscriptable
```

**Comment by hauntsaninja** [comment]
I can't reproduce / it's unlikely that changes in blobfile are causing this. Could you be more specific about what problem you're facing (e.g. provide stacktrace, Python version, etc)

**Comment by hauntsaninja** [comment]
blobfile 2.1.1 will fix the second error you're seeing (on Python 3.8). The first issue seems different, could you provide a repro?

Separately, I'll make it so that tiktoken uses blobfile even less than it already does.
