### ISSUE TITLE
ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by 2anirban** [openai/tiktoken#215]
Was trying to upload the project in Google Cloud run..using python 3.11.5
Not able to build wheels for Tiktoken..Tried every version. Can anybody help.

"Building wheel for tiktoken (pyproject.toml): started
  Building wheel for tiktoken (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  ? Building wheel for tiktoken (pyproject.toml) did not run successfully.
  ? exit code: 1
  ??> [37 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/tiktoken
      copying tiktoken/load.py -> build/lib.linux-x86_64-cpython-312/tiktoken
      copying tiktoken/core.py -> build/lib.linux-x86_64-cpython-312/tiktoken
      copying tiktoken/registry.py -> build/lib.linux-x86_64-cpython-312/tiktoken
      copying tiktoken/__init__.py -> build/lib.linux-x86_64-cpython-312/tiktoken
      copying tiktoken/model.py -> build/lib.linux-x86_64-cpython-312/tiktoken
      creating build/lib.linux-x86_64-cpython-312/tiktoken_ext
      copying tiktoken_ext/openai_public.py -> build/lib.linux-x86_64-cpython-312/tiktoken_ext
      running egg_info
      writing tiktoken.egg-info/PKG-INFO
      writing dependency_links to tiktoken.egg-info/dependency_links.txt
      writing requirements to tiktoken.egg-info/requires.txt
      writing top-level names to tiktoken.egg-info/top_level.txt
      reading manifest file 'tiktoken.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'Makefile'
      adding license file 'LICENSE'
      writing manifest file 'tiktoken.egg-info/SOURCES.txt'
      copying tiktoken/py.typed -> build/lib.linux-x86_64-cpython-312/tiktoken
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiktoken
  Building wheel for yarl (pyproject.toml): started
  Building wheel for yarl (pyproject.toml): finished with status 'done'
  Created wheel for yarl: filename=yarl-1.9.2-cp312-cp312-linux_x86_64.whl size=285235 sha256=74068f72957a1a126a9b7b237663c56f66563b61765f0308972e87cf6c4d4be2
  Stored in directory: /root/.cache/pip/wheels/84/e3/6a/7d0fa1abee8e4aa39922b5bd54689b4b5e4269b2821f482a32
  Building wheel for multidict (pyproject.toml): started
  Building wheel for multidict (pyproject.toml): finished with status 'done'
  Created wheel for multidict: filename=multidict-6.0.4-cp312-cp312-linux_x86_64.whl size=114928 sha256=8b8c43433d60abce6a0995ad8d0be737bb757d67a6181f9137a0054d8d273e91
  Stored in directory: /root/.cache/pip/wheels/f6/d8/ff/3c14a64b8f2ab1aa94ba2888f5a988be6ab446ec5c8d1a82da
Successfully built bs4 frozenlist yarl multidict
Failed to build tiktoken
ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
"

**Comment by mohaned-dewedar** [comment]
Running into this same issue right now.

**Comment by jonomacx** [comment]
I had code that was working yesterday when I was on Python 3.10, today I have upgraded to 3.12 and am using a virtualenv and I am now hitting the same issue.  Unsure if the versioning has played a part.

**Comment by TJaenichen** [comment]
Can confirm, installed from the rust website, restarted the command line and it works (win 10)

**Comment by bongaaa9123ds** [comment]
running into the same error

**Comment by bongaaa9123ds** [comment]
Collecting fleet-context
  Downloading fleet_context-1.1.9-py3-none-any.whl.metadata (13 kB)
Collecting openai>1.1.0 (from fleet-context)
  Downloading openai-1.3.5-py3-none-any.whl.metadata (16 kB)
Collecting rich>=13.0.0 (from fleet-context)
  Downloading rich-13.7.0-py3-none-any.whl.metadata (18 kB)
Collecting tiktoken>=0.3.3 (from fleet-context)
  Downloading tiktoken-0.5.1.tar.gz (32 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting anyio<4,>=3.5.0 (from openai>1.1.0->fleet-context)
  Downloading anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting distro<2,>=1.7.0 (from openai>1.1.0->fleet-context)
  Downloading distro-1.8.0-py3-none-any.whl (20 kB)
Collecting httpx<1,>=0.23.0 (from openai>1.1.0->fleet-context)
  Downloading httpx-0.25.2-py3-none-any.whl.metadata (6.9 kB)
Collecting pydantic<3,>=1.9.0 (from openai>1.1.0->fleet-context)
  Downloading pydantic-2.5.2-py3-none-any.whl.metadata (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.2/65.2 kB 10.4 kB/s eta 0:00:00
Collecting tqdm>4 (from openai>1.1.0->fleet-context)
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 101.0 kB/s eta 0:00:00
Collecting typing-extensions<5,>=4.5 (from openai>1.1.0->fleet-context)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.0.0->fleet-context)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=13.0.0->fleet-context)
  Downloading pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting regex>=2022.1.18 (from tiktoken>=0.3.3->fleet-context)
  Downloading regex-2023.10.3-cp312-cp312-win_amd64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 126.9 kB/s eta 0:00:00
Collecting requests>=2.26.0 (from tiktoken>=0.3.3->fleet-context)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting idna>=2.8 (from anyio<4,>=3.5.0->openai>1.1.0->fleet-context)
  Downloading idna-3.5-py3-none-any.whl.metadata (9.9 kB)
Collecting sniffio>=1.1 (from anyio<4,>=3.5.0->openai>1.1.0->fleet-context)
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting certifi (from httpx<1,>=0.23.0->openai>1.1.0->fleet-context)
  Downloading certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai>1.1.0->fleet-context)
  Downloading httpcore-1.0.2-py3-none-any.whl.metadata (20 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->openai>1.1.0->fleet-context)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 219.3 kB/s eta 0:00:00
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.0.0->fleet-context)
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting annotated-types>=0.4.0 (from pydantic<3,>=1.9.0->openai>1.1.0->fleet-context)
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.5 (from pydantic<3,>=1.9.0->openai>1.1.0->fleet-context)
  Downloading pydantic_core-2.14.5-cp312-none-win_amd64.whl.metadata (6.6 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.26.0->tiktoken>=0.3.3->fleet-context)
  Downloading charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.26.0->tiktoken>=0.3.3->fleet-context)
  Downloading urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: colorama in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from tqdm>4->openai>1.1.0->fleet-context) 
(0.4.6)
Downloading fleet_context-1.1.9-py3-none-any.whl (25 kB)
Downloading openai-1.3.5-py3-none-any.whl (220 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.8/220.8 kB 345.2 kB/s eta 0:00:00
Downloading rich-13.7.0-py3-none-any.whl (240 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.6/240.6 kB 446.5 kB/s eta 0:00:00
Downloading anyio-3.7.1-py3-none-any.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.9/80.9 kB 118.9 kB/s eta 0:00:00
Downloading httpx-0.25.2-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 106.3 kB/s eta 0:00:00
Downloading httpcore-1.0.2-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.9/76.9 kB 129.5 kB/s eta 0:00:00
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 235.6 kB/s eta 0:00:00
Downloading pydantic-2.5.2-py3-none-any.whl (381 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.9/381.9 kB 432.6 kB/s eta 0:00:00
Downloading pydantic_core-2.14.5-cp312-none-win_amd64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 380.1 kB/s eta 0:00:00
Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 325.5 kB/s eta 0:00:00
Downloading regex-2023.10.3-cp312-cp312-win_amd64.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.0/269.0 kB 280.6 kB/s eta 0:00:00
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 222.7 kB/s eta 0:00:00
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 256.7 kB/s eta 0:00:00
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 216.3 kB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.4/100.4 kB 39.5 kB/s eta 0:00:00
Downloading idna-3.5-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 102.7 kB/s eta 0:00:00
Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.6/104.6 kB 172.5 kB/s eta 0:00:00
Building wheels for collected packages: tiktoken
  Building wheel for tiktoken (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for tiktoken (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\tiktoken
      copying tiktoken\core.py -> build\lib.win-amd64-cpython-312\tiktoken
      copying tiktoken\load.py -> build\lib.win-amd64-cpython-312\tiktoken
      copying tiktoken\model.py -> build\lib.win-amd64-cpython-312\tiktoken
      copying tiktoken\registry.py -> build\lib.win-amd64-cpython-312\tiktoken
      copying tiktoken\_educational.py -> build\lib.win-amd64-cpython-312\tiktoken
      copying tiktoken\__init__.py -> build\lib.win-amd64-cpython-312\tiktoken
      creating build\lib.win-amd64-cpython-312\tiktoken_ext
      copying tiktoken_ext\openai_public.py -> build\lib.win-amd64-cpython-312\tiktoken_ext
      running egg_info
      writing tiktoken.egg-info\PKG-INFO
      writing dependency_links to tiktoken.egg-info\dependency_links.txt
      writing requirements to tiktoken.egg-info\requires.txt
      writing top-level names to tiktoken.egg-info\top_level.txt
      reading manifest file 'tiktoken.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'Makefile'
      adding license file 'LICENSE'
      writing manifest file 'tiktoken.egg-info\SOURCES.txt'
      copying tiktoken\py.typed -> build\lib.win-amd64-cpython-312\tiktoken
      running build_ext
      running build_rust
      error: can't find Rust compiler
     
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
     
      To update pip, run:
     
          pip install --upgrade pip
     
      and then retry package installation.
     
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiktoken
Failed to build tiktoken
ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects

**Comment by TJaenichen** [comment]
Like I wrote, installing rust fixed it for me.

**Comment by hauntsaninja** [comment]
OP's problem is that they're not using Python 3.11, they're using Python 3.12. tiktoken doesn't yet have 3.12 wheels uploaded to PyPI, so you'll fall back to sdist and compilation, which is why you would need Rust compiler. I'll add 3.12 wheels soon.

**Comment by Yunhua468** [comment]
> OP's problem is that they're not using Python 3.11, they're using Python 3.12. tiktoken doesn't yet have 3.12 wheels uploaded to PyPI, so you'll fall back to sdist and compilation, which is why you would need Rust compiler. I'll add 3.12 wheels soon.
> 
> Closing as a duplicate of #205

Down grade python version from 3.12 to 3.11, it works for me.

**Comment by hauntsaninja** [comment]
tiktoken 0.5.2 and newer support Python 3.12

**Comment by gokulcoder7** [comment]
> Can confirm, installed from the rust website, restarted the command line and it works (win 10)


how you installed rustup for windows 10 os?
