### ISSUE TITLE
encoding_for_model("gpt-4")

### ISSUE THREAD

**Issue by fanpeeps** [openai/tiktoken#220]
Readme suggestions selecting appropraite tokenizer with this request for gpt-4:

`enc = tiktoken.encoding_for_model("gpt-4")`

Yet, when doing so, this error is produced:

`ValueError: Unknown encoding gpt-4. Plugins found: ['tiktoken_ext.openai_public']`

**Comment by hauntsaninja** [comment]
That sounds like you ran `tiktoken.get_encoding("gpt-4")` instead of `tiktoken.encoding_for_model("gpt-4")`
