### ISSUE TITLE
Please add new mode gpt-3.5-turbo-instruct

### ISSUE THREAD

**Issue by kensenjohn** [openai/tiktoken#223]
Please add the new model

gpt-3.5-turbo-instruct

https://platform.openai.com/docs/models/gpt-3-5

<img width="780" alt="image" src="https://github.com/openai/tiktoken/assets/700520/2e1d723d-cdad-4e40-8971-508d33195be5">

**Comment by hauntsaninja** [comment]
```
>>> import tiktoken
>>> tiktoken.encoding_for_model("gpt-3.5-turbo-instruct")
<Encoding 'cl100k_base'>
```
This works fine on recent tiktoken
