### ISSUE TITLE
How to install 0.3.3?

### ISSUE THREAD

**Issue by AZmisc** [openai/tiktoken#224]
Hi, the text-webui tells me it needs tiktoken 0.3.3 to run. Could you please help me how can I install 0.3.3? (I am on Windows.) Thank you.

Error message: 

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230918 requires tiktoken==0.3.3, but you have tiktoken 0.5.2 which is incompatible.`

**Comment by hauntsaninja** [comment]
`pip install tiktoken==0.3.3`. ChatGPT is pretty good at answering this kind of question :-)
