### ISSUE TITLE
Pickling tokenizer fails due to builtins.CoreBPE

### ISSUE THREAD

**Issue by jerheff** [openai/tiktoken#231]
I am using tiktoken in a dataset preprocessing step for a pytorch [DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader).  They support multiprocessing in creating batches which spawns workers.  This fails with exception:

TypeError: cannot pickle 'builtins.CoreBPE' object

I am not familiar with Rust, but this [thread](https://github.com/PyO3/pyo3/issues/100) seems to suggest that a few methods in the Rust implementation would enable pickling the tokenizer.

**Comment by sk-g** [comment]
+1

Fails with this error when used in multiprocessing context, eg

```python3

    train_dataset = train_dataset.map(
        tokenization_function,
        batched=True,
        batch_size=1000,
        num_proc=args.num_proc,
        load_from_cache_file=not args.overwrite_cache,
        desc=f"Running tokenizer on train dataset with {len(train_dataset)} items"
        )
```

**Comment by sk-g** [comment]
Related issue: https://github.com/openai/tiktoken/pull/181

**Comment by hauntsaninja** [comment]
I allow Encoding to be pickled in tiktoken 0.6. Please let me know if the implementation doesn't work well for you!

**Comment by jerheff** [comment]
@hauntsaninja Works for me. Thanks!
