### ISSUE TITLE
new method to truncate after N-tokens

### ISSUE THREAD

**Issue by aleks-sch** [openai/tiktoken#236]
hi there!

## issue description/motivation 
We've a use-case where we would like to quickly and maximally truncate an input string after N-tokens.

Where trying to repeatedly count tokens for a substring risks that including next few chars would actually the bring token count down.

<img width="110" alt="image" src="https://github.com/openai/tiktoken/assets/141164101/85acd241-103c-45cf-af75-49ac21d9604f">

## proposed approach
I am keen to put together a PR to do this - I am interested in coding more Rust and it feels doable. Making the change in the Rust code would prevent us from having to perform multiple calls to `Encoding.encode` and counting tokens for growing substrings.

suggested approach follow signature of `Encoding.decode_with_offsets` 
https://github.com/openai/tiktoken/blob/9e79899bc248d5313c7dd73562b5e211d728723d/tiktoken/core.py#L279-L302

e.g. 

```python
really_long_str = "really long input string..."
encoding.truncate_after_n_tokens(inp=really_long_str, n_tokens=2)
"really long", [54760, 1317]
```

## specific questions
- initial thoughts on this? feasibility, anything I am missing before I start?
- your early support to review a PR?

thanks!

**Comment by apouliotfigma** [comment]
Why not tokenize the string, then truncate the list of tokens to `[0,N)` instead?

**Comment by aleks-sch** [comment]
thanks - that is super simple and solves my problem!

closing the issue
