### ISSUE TITLE
Could I train this tokenizer using my own data from scratch?

### ISSUE THREAD

**Issue by Zephyr1022** [openai/tiktoken#25]

**Comment by hauntsaninja** [comment]
Yes, but we don't provide training code. Note that token index must be equivalent to merge priority and specific merges must not be disallowed. Best of luck!

**Comment by StephennFernandes** [comment]
@hauntsaninja hey is this still the case ? 

as llama 3 and phi3 have trained their modles on tiktoken. 

But still i couldn't find any resources/ documentation on how to train my very own tiktoken tokenizer.

**Comment by alxmamaev** [comment]
@StephennFernandes I guess you need use third party trainer and then just convert it to TT format, so actually seems it just inference code there.
