### ISSUE TITLE
Unsound transmute in lib

### ISSUE THREAD

**Issue by MolotovCherry** [openai/tiktoken#26]
Just a small note, but the `repr(Rust)` memory layout does not guarantee that two similarly defined structs are laid out the exact same way in memory. Thus, transmutes between `repr(Rust)` types are UB.

For reference, please see this nomicon article here:
https://doc.rust-lang.org/nomicon/repr-rust.html

> Rust does guarantee that two instances of A have their data laid out in exactly the same way. However Rust does not currently guarantee that an instance of A has the same field ordering or padding as an instance of B.

The struct in question requires a `repr(transparent)` or `repr(C)` to be safe. However, `ThreadId` does not have any of these on it, so putting it only on one will do little good.

https://github.com/openai/tiktoken/blob/156eff92d2dc88e108bdece47e584b05859af557/src/lib.rs#L120

**Comment by hauntsaninja** [comment]
Thanks for the note!

I agree that it's not safe by the book, but I do have those const checks that make sure they're both u64, which I think means that this should be fine in practice... Also even if the two u64 are laid out differently, that's fine for this application, the value here matters very little.

With that said, I'd love to use safe code if you see something that would work on stable! As I mention in the comment https://github.com/rust-lang/rust/issues/67939 is nightly only and I don't want to deal with the headache of nightly toolchain.
