### ISSUE TITLE
Can't install tiktoken==0.4.0 or tiktoken==0.5.1in Python 3.12 

### ISSUE THREAD

**Issue by JackObid** [openai/tiktoken#264]
If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
     
      To update pip, run:
     
          pip install --upgrade pip
     
      and then retry package installation.
     
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiktoken
Failed to build tiktoken
ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects

**Comment by JackObid** [comment]
This eventual worked 
RUN pip install --upgrade pip && pip install setuptools==69.0.1
RUN pip install tiktoken==0.5.2

**Comment by hauntsaninja** [comment]
Versions of tiktoken before 0.5.2 did not build Python3.12 wheels, see https://github.com/openai/tiktoken/blob/main/CHANGELOG.md#v052
If you want to use older versions with Python 3.12, you'll need to compile from sdist, which will require a rust compiler as the error message above is telling you.

**Comment by JamesClarke7283** [comment]
Seems resolved.

The main issue around 3.12 #205 was locked, so i will Just an update for context(some regression testing won't hurt), here are the tests for tiktoken 0.9.0 (commit: e35ab09) I ran this today (timestamp: 21/06/2025, 9:30-ish BST)
```
❯ pytest tests --import-mode=append
====================== test session starts =======================
platform linux -- Python 3.12.10, pytest-8.4.1, pluggy-1.6.0
rootdir: /tmp/tiktoken
configfile: pyproject.toml
plugins: hypothesis-6.135.14
collected 30 items

tests/test_encoding.py ......................              [ 73%]
tests/test_misc.py ..                                      [ 80%]
tests/test_offsets.py ..                                   [ 86%]
tests/test_pickle.py .                                     [ 90%]
tests/test_simple_public.py ...                            [100%]

======================= 30 passed in 4.02s =======================
```
Full reproducible command path & verbose test logs:
[tiktoken-0.9.0-py312-setup+tests.log](https://github.com/user-attachments/files/20845783/tiktoken-0.9.0-py312-tests.log)

System specs (if needed):
```
OS: Arch Linux x86_64
Kernel: Linux 6.15.2-arch1-1
Shell: zsh 5.9
CPU: AMD Ryzen 7 5700G (16) @ 4.67 GHz
GPU: NVIDIA GeForce RTX 4070 [Discrete]
Memory: 10.89 GiB / 62.58 GiB (17%)
Swap: Disabled
Disk (/): 1.80 TiB / 1.82 TiB (99%) - xfs
```
