### ISSUE TITLE
API models to .tiktoken mapping?

### ISSUE THREAD

**Issue by spolu** [openai/tiktoken#27]
Hi! Could you confirm if the following mappings are accurate?

code-davinci-002 -> p50k_base.tiktoken
text-\*-003 -> p50k_base.tiktoken
text-\*-002 -> p50k_base.tiktoken
text-\*-001 -> r50k_base.tiktoken
embeddings-\*-001 -> r50k_base.tiktoken
embeddings-\*-002 -> cl100k_base.tiktoken

**Comment by spolu** [comment]
Ah! This is confirmed here: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

**Comment by hauntsaninja** [comment]
Good to see you! I'll be releasing a version of tiktoken in a day or two that has the mapping as well :-)

**Comment by spolu** [comment]
🔥

**Comment by hauntsaninja** [comment]
I just released v0.2.0 that lets you do `tiktoken.encoding_for_model("text-davinci-003")`
