### ISSUE TITLE
Encode an empty string gives empty tokens

### ISSUE THREAD

**Issue by flexwang** [openai/tiktoken#276]
`tiktoken.encode('')` will return an empty list. However, for huggingface tokenizer, encode an empty string will yield `eos_token`. Is there a way to make `tiktoken` behave the same way?

**Comment by pratyakshagarwal** [comment]
i added a contidion where if the text input is empty then it's gonna return the eos_token

**Comment by hauntsaninja** [comment]
Use `tiktoken.encode('') or [eos_token]`
