### ISSUE TITLE
Using offline: `.tiktoken` file gets deleted automatically on Linux

### ISSUE THREAD

**Issue by nkilm** [openai/tiktoken#279]
## Description

I'm trying to setup tiktoken locally with the help of this guide - https://stackoverflow.com/questions/76106366/how-to-use-tiktoken-in-offline-mode-computer. But the problem I'm facing is that the **.tiktoken** file - `cl100k_base.tiktoken` is getting deleted automatically after code execution on Linux machine.

OS: Linux 
tiktoken version - `0.6.0`

**Comment by Yuxiang1995** [comment]
I meet the same question!

**Comment by Yuxiang1995** [comment]
cl100k_base.tiktoken was updated, download the latest version can fix it

**Comment by nkilm** [comment]
@Yuxiang1995 Thanks! I'll checkout and let you know.

**Comment by nkilm** [comment]
**Update:** Latest version of `.tiktoken` fixes this issue.
