### ISSUE TITLE
Improve packaging metadata for PyPI

### ISSUE THREAD

**Issue by goodmami** [openai/tiktoken#28]
The [tiktoken](https://pypi.org/project/tiktoken/) package on PyPI could use some metadata to indicate that it is an official OpenAI project because, unlike this repo, the project on PyPI does not mention its link to OpenAI at all.

* Add the [openai](https://pypi.org/user/openai/) user as an author or maintainer
* Link back to this repo as the project homepage
* Use the README as a project description

These steps help because [phishing](https://www.techtarget.com/searchsoftwarequality/news/252524191/PyPI-phishing-renews-call-for-mandatory-2FA-package-signing) and other security issues are a problem on PyPI, and linking back to this OpenAI-controlled repo (which then indicates the proper package in PyPI to install) provide a signal that it's a legit package, at least for those of us who double-check package sources before `pip install`ing :)

**Comment by zihaolucky** [comment]
Another question, is it possible to support py36?

**Comment by hauntsaninja** [comment]
goodmami, thanks for the suggestion, will make sure to include more metadata in the next release

**Comment by hauntsaninja** [comment]
zihaolucky, that's unrelated to this issue. As stated in https://github.com/openai/tiktoken/issues/1#issuecomment-1370274880 , I will not be adding support for Python 3.7 or 3.6. Python 3.6 has been end of life for over a year, so I strongly recommend against using it in production.

**Comment by hauntsaninja** [comment]
Fixed in 0.3.0. Thanks for the suggestion! :-)
