### ISSUE TITLE
Tiktoken not installing on a macbook pro with m2 chip

### ISSUE THREAD

**Issue by chaudhryna** [openai/tiktoken#286]
I'm trying to install tiktoken per the documentation but the program looks at all the versions of tiktoken to see which is compatible and then errors out when trying to install them with a message:

ERROR: Cannot install tiktoken==0.1.1, tiktoken==0.1.2, tiktoken==0.2.0, tiktoken==0.3.0, tiktoken==0.3.1, tiktoken==0.3.2, tiktoken==0.3.3, tiktoken==0.4.0, tiktoken==0.5.0, tiktoken==0.5.1, tiktoken==0.5.2 and tiktoken==0.6.0 because these package versions have conflicting dependencies.

Which version of tiktoken will work with the m2 chip and what's the best way to install it?

**Comment by ai-nikolai** [comment]
I was able to install `tiktoken==0.6.0` on M2 using pip.

**Comment by hauntsaninja** [comment]
> conflicting dependencies

Indicates it's something to do with some other dependencies you're pinning
