### ISSUE TITLE
Exception has occurred: ConnectionError HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F4D42B0EE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

### ISSUE THREAD

**Issue by anithamudigoudar** [openai/tiktoken#287]

**Comment by zhuiyue132** [comment]
i have same question

**Comment by hauntsaninja** [comment]
You're encountering some network issue while downloading the vocabularies.

If you don't have network access where you're running this, you can predownload and use `TIKTOKEN_CACHE_DIR` or something to avoid. See https://github.com/openai/tiktoken/issues/281
