### ISSUE TITLE
I want to modify the code in self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)

### ISSUE THREAD

**Issue by zzzfffsss** [openai/tiktoken#302]
If I want to modify the code in self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors), then do I have to modify the _tiktoken.cpython-39-x86_64-linux-gnu.so file

**Comment by hauntsaninja** [comment]
Yes, methods on `self._core_bpe` are native code, not Python
