### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Hudrolax** [openai/tiktoken#323]
Got RecursionError in the line:
```
encoding = tiktoken.encoding_for_model("gpt-4o")
```
Any ideas?

python:3.11.4-alpine3.18 (Docker)
tiktoken==0.7.0

**Comment by AnshulV98** [comment]
@Hudrolax did you find a solution to this? Encountered a similar issue right now

**Comment by Hudrolax** [comment]
@AnshulV98 In my case there was indeed a recursive method call due to a logical error in the code.

**Comment by AnshulV98** [comment]
was it necessarily related to tiktoken or was it some other part of the code?

**Comment by Hudrolax** [comment]
@AnshulV98 The problem was in my code, not tiktoken

**Comment by AnshulV98** [comment]
@Hudrolax last question, did you get this for code execution or unit testing? It works for me for code execution but not for unit testing
