### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1) when tiktoken.get_encoding("cl100k_base")

### ISSUE THREAD

**Issue by hzh12345678** [openai/tiktoken#330]
As the title, ValueError: not enough values to unpack (expected 2, got 1) when tiktoken.get_encoding("cl100k_base")
<img width="963" alt="Screenshot 2024-08-02 231714" src="https://github.com/user-attachments/assets/96dc8e03-ccc1-4357-8cd1-fa47b0488511">

**Comment by hauntsaninja** [comment]
Hm, it looks like the vocabulary file is corrupted or something. Recent versions of tiktoken will run hash checks against downloaded vocabularies. If you can reproduce with latest tiktoken (0.8) please re-open the issue

**Comment by johnsutor** [comment]
Getting this error within the transformers library, please see https://github.com/huggingface/transformers/issues/33746
