### ISSUE TITLE
Is there a new tokenizer for o1 models?

### ISSUE THREAD

**Issue by jiadingfang** [openai/tiktoken#337]
Hi openai devs,

Congrats on releasing o1 models, and I'm excited to test them out. Since there seems to be new "reasoning" tokens in generation, I wonder if there is a new version for tiktoken for o1 models?

Thanks in advance!

**Comment by kotikkonstantin** [comment]
@jiadingfang I suspect it's same as gpt-4o has

**Comment by Rameenh** [comment]
I am curious about this as well.

**Comment by llv22** [comment]
I'm also curious about it

**Comment by mrsbeep** [comment]
I'm also very curious about this issue. It seems to be basically the same as the gpt-4o model, but it seems to me that it includes some other tokens.

**Comment by Ki-Seki** [comment]
Curious +1

**Comment by senghorn** [comment]
Need this support!

**Comment by archasek** [comment]
Why `tiktoken.encodingForModel("gpt-4o-mini")` still doesn't work?
`Error: No tokenizer found for model gpt-4o-mini`

**Comment by enricoros** [comment]
I see different input token counts between o1-preview and gpt-4o. Probably a different tokenizer.

**Comment by hauntsaninja** [comment]
This is fixed in tiktoken 0.8. Yes, from user's perspective the o1 tokeniser works the same way as 4o tokeniser

**Comment by mavroudisv** [comment]
@hauntsaninja can I assume that if a model is explicitly supported by tiktoken then we know which tokenizer is used? 

Or are tokenizers best-effort and there may be smaller or larger discrepancies (e.g., non-english languages or symbols) between the tokenizer tiktoken uses and what's used by the provider?

**Comment by mavroudisv** [comment]
ok responding to my question and others:

All models up to GPT4.5 (the latest model currently) appear to use the same tokenizer as 4o.
The only exception is o1-preview, which is quite different. 

If your goal is to know more or less how many tokens you will transmit, it's probably ok.

I don't have inside information, this is through my own experiments.
