### ISSUE TITLE
some tokens begin with extra space

### ISSUE THREAD

**Issue by Majdoddin** [openai/tiktoken#34]
23 of the tiktoken tokens are different from that of GPT2TokenizerFast, in that they start with an extra space ' '.
So why is it like that, and how can I remove that ' ' from these tokens?

This is the code:

```python
import tiktoken
from transformers import GPT2TokenizerFast

tik = tiktoken.get_encoding("gpt2")
hug2 = GPT2TokenizerFast.from_pretrained("gpt2")

print(hug2.vocab_size)    # 50257
print(len(tik.token_byte_values()))    # 50256

for i in range(50257):
    if tik.decode([i]) != hug2.decode(i):
        print(i, tik.decode([i]), hug.decode([i]))       
print(count)
```

output:
```
764  . .
837  , ,
2644  ... ...
5145  ! !
5633  ? ?
11485  .. ..
14512  != !=
19153  ?? ??
19424  .... ....
20004  ........ ........
22135  ." ."
24457  ./ ./
34913  ??? ???
35713  ..." ..."
37867  !! !!
39864  .......... ..........
41349  ?) ?)
42911  ," ,"
44713  ................ ................
44912  .............. ..............
46328  .) .)
47082  ...... ......
47540  ._ ._
```

**Comment by hauntsaninja** [comment]
Huh, that's interesting. Seems like that's a bug in `GPT2TokenizerFast`.
GPT-2 was a model trained by us and `tiktoken` uses the vocab and encoder files directly from our open source GPT-2 release.

See:
- https://github.com/openai/gpt-2/blob/a74da5d99abaaba920de8131d64da2862a8f213b/download_model.py#L17
- https://github.com/openai/tiktoken/blob/7830ed537badecefb5a357448be722bfd58f9fca/tiktoken_ext/openai_public.py#L11

Also it makes no sense to have duplicate tokens, e.g. `?` is already token 30.

As for what you can do:
- File a bug at huggingface
- Create your own tiktoken.Encoding object directly that has the (buggy) encoding information that you want

**Comment by hauntsaninja** [comment]
Huh, it looks like only huggingface's decoder is broken:

```
>>> hug2.decode(hug2.encode(" ?"))
'?'
```

**Comment by hauntsaninja** [comment]
Filed an issue at https://github.com/huggingface/tokenizers/issues/1164
