### ISSUE TITLE
Supporting python 3.7 for tiktoken

### ISSUE THREAD

**Issue by hatrandev** [openai/tiktoken#35]
Hi @hauntsaninja , Thank you very much for your works on Tiktoken, by supporting both 3.8 and 3.9

Could you please help to support 3.7 python version? Or could you give a guidance on where it is feasible to do so and if it is feasible, how we should do?

Thank you!

**Comment by hauntsaninja** [comment]
Thanks for your interest in tiktoken! :-)

I'm not planning on supporting Python 3.7. Python 3.7 will be end-of-life in four months, I'd recommend switching away from it in production. Many projects in the scientific ecosystem have dropped support for 3.7, for example, numpy

You're welcome to fork. You'd at least need to replace use of cached_property and the walrus operator, but there are probably other things as well.
