### ISSUE TITLE
Keep getting tiktoken errors when running my code

### ISSUE THREAD

**Issue by Byzzee-gh** [openai/tiktoken#355]
Full disclosure: I am a complete noob with coding. 

I am a fan of the youtuber DougDoug and I am trying to set up a program he wrote that allows me to speak to an AI and have it speak back to me verbally. He has the code publicly available so I got it and did the necessary steps of obtaining the API's that I needed, but when I run it I get this: 
![image](https://github.com/user-attachments/assets/967003f3-0934-4016-a08c-4bd36ade5cb1)

I am attempting to make sense of it, but haven't been able to make heads or tails of my problem. The link provided in the NotImplementedError doesn't take me anywhere. I've tried some googling but am not sure how to apply the advice others received for their cases to mine. Like I said, total noob.

Not sure if it helps but here is a link to the code: [https://github.com/DougDougGithub/Babagaboosh](url)

**Comment by hauntsaninja** [comment]
Use a newer version of tiktoken
