### ISSUE TITLE
Why is the word vector file corresponding to GPT so small?

### ISSUE THREAD

**Issue by Cristliu** [openai/tiktoken#356]
Models like cl100k_base.json are too small? A lot of words don't have corresponding representations. But I'm wondering if I end up using a model like gpt-3.5, and I use a larger scale word vector file like GloVe.840B.300d.txt, will it affect the effectiveness of the final gpt-3.5 task?

**Comment by hauntsaninja** [comment]
It's not vectors, just tokens (aka indices). The vectors are inside the model :-)
