### ISSUE TITLE
Question on tiktoken vs. GPT2Tokenizer

### ISSUE THREAD

**Issue by hatrandev** [openai/tiktoken#38]
Hi @hauntsaninja, 

Could I understand that tiktoken works similar to GPT2Tokenizer?

If yes, could you tell me more what is the same and what is the difference for these two?

Thank you!

**Comment by hauntsaninja** [comment]
If by `GPT2Tokenizer` you mean huggingface's `GPT2Tokenizer`, yes they should work similarly — except tiktoken should be significantly faster. Also note that hugginface's `GPT2Tokenizer` has some minor bugs, see e.g. https://github.com/openai/tiktoken/issues/34

If by GPT2Tokenizer you mean the reference tokeniser in https://github.com/openai/gpt-2 , the behaviour is equivalent

**Comment by hatrandev** [comment]
Thanks @hauntsaninja very much for your answer! May I please have follow up question?

I used Huggingface's GPT2Tokenizer, with below code:

from transformers import GPT2Tokenizer
enc = GPT2Tokenizer.from_pretrained("gpt2")


Given the minor bugs on #34 (23/50275)
_a. could you tell if you think the tokenized results should be comparable for both Tiktoken and Huggingface's GPT2Tokenizer?_
b. If I would like to fix this, could you suggest me? should I make the change directly here, from the vocab.json file of Huggingface's GPT2 or instead of using this vocab.json, I changed to use encoder.json from gpt-2 (the reason is I hope to use Huggingface's GPT2Tokenizer because I would need to use python 3.7):

![image](https://user-images.githubusercontent.com/117962652/221718711-8e113414-b153-47aa-99df-7b2878c9aa3c.png)

c. for this,  https://github.com/openai/gpt-2, could you tell me how I can use tokenizer? I don't see the function/example for this

Thank you!
