### ISSUE TITLE
Follow up question on #https://github.com/openai/tiktoken/issues/38

### ISSUE THREAD

**Issue by hatrandev** [openai/tiktoken#39]
Hi @hauntsaninja , seems that github doesn't give me the way to send message for questions, so could I have follow up questions on the closed issue https://github.com/openai/tiktoken/issues/38? Thank you very much. I will close the issue up after.

-----------------------------------------
Follow up question in https://github.com/openai/tiktoken/issues/38:

I used Huggingface's GPT2Tokenizer, with below code:

from transformers import GPT2Tokenizer
enc = GPT2Tokenizer.from_pretrained("gpt2")

Given the minor bugs on https://github.com/openai/tiktoken/issues/34 (23/50275)
a. could you tell if you think the tokenized results should be comparable for both Tiktoken and Huggingface's GPT2Tokenizer?
b. If I would like to fix this, could you suggest me? should I make the change directly here, from the vocab.json file of Huggingface's GPT2 or instead of using this vocab.json, I changed to use encoder.json from gpt-2 (the reason is I hope to use Huggingface's GPT2Tokenizer because I would need to use python 3.7):

image

c. for this, https://github.com/openai/gpt-2, could you tell me how I can use tokenizer? I don't see the function/example for this

Thank you!

Thanks @hauntsaninja very much for your answer! May I please have follow up question?

I used Huggingface's GPT2Tokenizer, with below code:

from transformers import GPT2Tokenizer
enc = GPT2Tokenizer.from_pretrained("gpt2")

Given the minor bugs on https://github.com/openai/tiktoken/issues/34 (23/50275)
a. could you tell if you think the tokenized results should be comparable for both Tiktoken and Huggingface's GPT2Tokenizer?
b. If I would like to fix this, could you suggest me? should I make the change directly here, from the vocab.json file of Huggingface's GPT2 or instead of using this vocab.json, I changed to use encoder.json from gpt-2 (the reason is I hope to use Huggingface's GPT2Tokenizer because I would need to use python 3.7):

image

c. for this, https://github.com/openai/gpt-2, could you tell me how I can use tokenizer? I don't see the function/example for this

Thank you!

**Comment by hauntsaninja** [comment]
You can just reply on the closed issue.

Yeah, the tokenised results should be comparable. The bug in huggingface in #34 only applies to the decoder.

You don't need to touch the vocab files.

The gpt-2 repo is small and Github has a nice search feature. But look in encoder.py
