### ISSUE TITLE
Tell Rust you're not going to change the map

### ISSUE THREAD

**Issue by abdurraheemali** [openai/tiktoken#4]
https://github.com/openai/tiktoken/blob/ab3688a4016b4530231690f430c702727bb0da24/src/lib.rs#L419-L421

**Comment by hauntsaninja** [comment]
Hello! Not sure why you've created an issue... I wrote that comment so I clearly already know about it ;-) If you want to change something, feel free to propose a PR. But in the meantime, I'm closing this, #5 and #6
