### ISSUE TITLE
Does tiktoken support CLIP's tokenizer?

### ISSUE THREAD

**Issue by vedantroy** [openai/tiktoken#41]
Hi! CLIP currently uses an ad-hoc tokenizer. I was wondering if tiktoken supports the codec that CLIP uses. Or, if by coincidence, CLIP's tokenizer is equivalent to--e.g--GPT2's.

**Comment by hauntsaninja** [comment]
tiktoken does not have an equivalent for CLIP's tokeniser. The underlying BPE code should be equivalent (although I haven't verified this) — but CLIP has additional preprocessing and uses a different vocabulary to the encodings tiktoken ships with.
