### ISSUE TITLE
Can you add the new ChatGPT API model `gpt-3.5-turbo`

### ISSUE THREAD

**Issue by Sea-Snell** [openai/tiktoken#42]
Can you add a mapping to the tokenizer for the new ChatGPTAPI model in [MODEL_TO_ENCODING](https://github.com/openai/tiktoken/blob/main/tiktoken/model.py)? Or if it doesn't correspond to one of the tokenizers already provided, can the tokenizer be added?

This would be really helpful! Thanks!

**Comment by edwardxwu** [comment]
+1 I noticed the tokenizer is definitely not the same for "text-davinci-003"

**Comment by logankilpatrick** [comment]
This will be fixed here: https://github.com/openai/tiktoken/pull/44

**Comment by Sea-Snell** [comment]
Thanks!

**Comment by hauntsaninja** [comment]
Just released tiktoken 0.3.0 with the needed changes
