### ISSUE TITLE
gpt-3.5-turbo model support

### ISSUE THREAD

**Issue by gobsimpacts0u** [openai/tiktoken#45]
Are you considering adding `gpt-3.5-turbo` model support?
Or should the `gpt2` model be used (according to https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb)?

**Comment by KineticCookie** [comment]
I'm also interested in `gpt-3.5-turbo` support.
Sometimes I need to calculate the number of tokens before sending it to the model.

**Comment by hauntsaninja** [comment]
Thanks for your interest in turbo and tiktoken! I've added support for turbo in `encoding_for_model` and released this in 0.3.0
