### ISSUE TITLE
Not able to Install TikToken : ERROR: Could not find a version that satisfies the requirement tiktoken (from versions: none

### ISSUE THREAD

**Issue by clcbot2020** [openai/tiktoken#46]
Hello 

we are not able to install Tikcoken , getting below Errors

ERROR: Could not find a version that satisfies the requirement tiktoken (from versions: none)
ERROR: No matching distribution found for tiktoken

Thanks

**Comment by hauntsaninja** [comment]
You'd need to provide more information than that. My guess is that you're trying to use tiktoken with Python 3.7. As stated in https://github.com/openai/tiktoken/issues/1#issuecomment-1370274880 , I will not be adding support for Python 3.7 or older. Python 3.6 has been end of life for over a year, so I strongly recommend against using it in production.
