### ISSUE TITLE
Java Alternative

### ISSUE THREAD

**Issue by HarryBouch96** [openai/tiktoken#49]
Does anyone know if a java alternative exists?

**Comment by hauntsaninja** [comment]
Someone made Java bindings for tiktoken here: https://github.com/eisber/tiktoken

Note that that is not a repository maintained by OpenAI and I cannot personally vouch for it.

**Comment by jiangying000** [comment]
need this

**Comment by tox-p** [comment]
I was facing a similar issue and decided to port the part of tiktoken that I needed to java. Maybe this is helpful to you: https://github.com/knuddelsgmbh/jtokkit

Currently (0.1.0) it is quite limited and only supports encoding and decoding of r50k_base, p50k_base, p50k_edit and cl100k_base and I am just slowly starting with benchmarking and performance optimizations right now

**Comment by hauntsaninja** [comment]
Thanks all! I'm closing this as a duplicate of https://github.com/openai/tiktoken/issues/97
