### ISSUE TITLE
How to make it support bigscience/bloom ?

### ISSUE THREAD

**Issue by hawgjmrd72** [openai/tiktoken#55]

**Comment by hauntsaninja** [comment]
Thanks for your interest in tiktoken! The API for the Encoding class is documented over here: https://github.com/openai/tiktoken/blob/ec7c121e385bf1675312c6c33734de6b392890c4/tiktoken/core.py#L26

**Comment by hawgjmrd72** [comment]
> Thanks for your interest in tiktoken! The API for the Encoding class is documented over here:
> 
> https://github.com/openai/tiktoken/blob/ec7c121e385bf1675312c6c33734de6b392890c4/tiktoken/core.py#L26

Yes, I already read it, but I still don't know how to make  the parameters such as pat_str, mergeable_ranks.
I was wonder if  bigscience/bloom share the same tokenizer whit GPT2 since there are both based on byte-level Byte-Pair-Encoding.

**Comment by hauntsaninja** [comment]
I'd look at the code they've shared to figure it out. I've only worked directly on OpenAI's models ;-)
