### ISSUE TITLE
how to generate _tiktoken_bg.wasm?

### ISSUE THREAD

**Issue by bigbigcoder** [openai/tiktoken#57]
hi! I wonder how to generate or download _tiktken_bg.wasm? Since i always encounter errors like "chatgpt activate error, not found _tiktken_bg.wasm" while debugging a vscode extension about chatgpt. Looking forward to your reply.

**Comment by hauntsaninja** [comment]
This repository does not currently ship WASM bindings. I'd ask the author of whatever unofficial extension you're using
