### ISSUE TITLE
tiktoken hangs when getting model encoding.

### ISSUE THREAD

**Issue by TravisChristensen** [openai/tiktoken#58]
Running in aws lambda, calling `tiktoken.encoding_for_model("gpt-3.5-turbo")` causes my script to hang. I found that there is some cache and set an environment variable `TIKTOKEN_CACHE_DIR` to `/tmp/` since lambdas have read only filesystem except /tmp but have had no luck.

**Comment by hauntsaninja** [comment]
Try setting `TIKTOKEN_CACHE_DIR=''` if you don't want tiktoken to cache

**Comment by TravisChristensen** [comment]
That didn't help either..hmm. Does tiktoken try to log anywhere special? All I see is a print() log right before the call to encoding_for_model and then nothing.

**Comment by hauntsaninja** [comment]
tiktoken doesn't do any logging. It does fetch the relevant encoding file from a storage location, e.g. https://github.com/openai/tiktoken/blob/ec7c121e385bf1675312c6c33734de6b392890c4/tiktoken_ext/openai_public.py#L26

**Comment by TravisChristensen** [comment]
My bad, it ended up not actually being tiktoken's fault but I learned how to download the file into the docker image to prevent having to download it many times which is a win at least. Thanks

**Comment by cscottsa** [comment]
@TravisChristensen @hauntsaninja  I came across this issue as I've also been getting this error. Although, I am not sure what a docker image has to do with your aws lambda function?

Based on my research all fingers are pointing to tiktoken, that points to its dependency numpy?
ChatGPT said: "OpenBLAS tries to determine the L2 cache size of the system to optimize its performance, but it's not able to do that in the AWS Lambda environment."

Would you mind please helping me out here. I'm not sure how to figure this out, as I'm not using docker, but I'm still getting this error.

**Comment by nkov** [comment]
@TravisChristensen what was the solution to this? i'm getting the same issue where `tiktoken` is hanging on `tiktoken.encoding_for_model('gpt-3.5-turbo')` when running on an AWS lambda with python 3.9, but works on my local machine.

external network access from the lambda is confirmed to be working since the rest of the code is able to interact with OpenAI APIs

**Comment by nkov** [comment]
Increasing the RAM available to the lambda from 128 MB to 256 MB fixed this.

**Comment by amoffat** [comment]
If you're building a Docker image, feel free to use these lines in your Dockerfile to help with caching:

```dockerfile
ARG ENCODING_MODEL=cl100k_base
# change this to force a re-download of the encoding
ARG ENCODING_CACHE_BUST=1
# don't use /tmp, because a cloud provider may mount ephemeral storage there,
# overwriting our cache
ENV TIKTOKEN_CACHE_DIR=/usr/local/share/tiktoken
ENV TIKTOKEN_ENCODING_URL=https://openaipublic.blob.core.windows.net/encodings/${ENCODING_MODEL}.tiktoken
RUN mkdir -p $TIKTOKEN_CACHE_DIR && \
    curl -L $TIKTOKEN_ENCODING_URL?cache=$ENCODING_CACHE_BUST > \
    $TIKTOKEN_CACHE_DIR/$( \
    python -c "import sys; import hashlib; print(hashlib.sha1(sys.argv[1].encode()).hexdigest())" \
    $TIKTOKEN_ENCODING_URL \
    )
```
