### ISSUE TITLE
Exporting BPE file to vocab/merges files used by Huggingface tokenizers

### ISSUE THREAD

**Issue by colinclement** [openai/tiktoken#60]
Do you have a tool for exporting the tokenizer BPE files for use in other BPE tokenizer libraries like Huggingface tokenizers? For example, can we convert the `encoder._mergeable_ranks` object to the standard `vocab.json` and `merges.txt` files used by the `tokenizers` library?

**Comment by hauntsaninja** [comment]
Mostly untested, but something on the lines of the following should work:
```
tokens = sorted(mergeable_ranks, key=lambda x: mergeable_ranks[x])
merges = {}
for token in tokens:
    if len(token) == 1:
        continue

    match = None
    for j in range(1, len(token)):
        left_token = mergeable_ranks.get(token[:j])
        right_token = mergeable_ranks.get(token[j:])
        if left_token is not None and right_token is not None:
            merge_max = max(left_token, right_token)
            if match is None or merge_max < match[0]:
                match = (merge_max, (token[:j], token[j:]))
    assert match is not None
    merges[token] = match[1]
    print(f"{token} = {match[1][0]} + {match[1][1]}")
```

**Comment by mikcnt** [comment]
@hauntsaninja first of all thanks! Unfortunately, I don't think that's going to work. Applying this to `r50k_base` (which should be the same tokenizer under the [GPT2 tokenizer](https://huggingface.co/gpt2/blob/main/merges.txt) on HF), produces results that are (slightly) different from the ones contained in the `merges.txt` [file](https://huggingface.co/gpt2/raw/main/merges.txt) provided by HuggingFace.

Look for example at line 347 of the `merges.txt` file provided by HF:
```
res s
```

Now, the token `ress` is splitted differently with the function you provide:
```python
merges[b"ress"]
# (b'r', b'ess')
```

There are a total of 3644 differences between the two, and, from my understanding, it has to do with the merge order: all of the different examples between the two version of `merges` happen when a token is splitted at a different position than the original merge.

Any suggestion?

**Comment by shenfe** [comment]
Hi @mikcnt do you have any finding on this problem?

**Comment by colinclement** [comment]
I have been poking around at this more. A question for someone more knowledgeable about encodings: if I take `tokens` from the above code snippet, and try `[t.decode('utf-8') for t in tokens]`, this fails because the tokens are bytes which are not necessarily expressible in utf-8, e.g. one token is `b'\xa1'`, which yields an invalid start byte error. However, when considering translating to HF tokenizers, even the ByteLevelBPETokenizer takes Python strings as its vocab and merges inputs. What am I missing?

**Comment by colinclement** [comment]
I answered my own question, it's also helpfully answered in [this comment in the code](https://github.com/openai/tiktoken/blob/82facf911fe41f39f13565be73899eab1e1761ef/tiktoken/core.py#L230). TL;DR: tiktoken does not assume tokens are valid UTF-8 byte sequences. I believe HF must impose the constraint of tokens being valid UTF-8 bytes as they assume their [vocab/merges objects are representable as Python strings](https://github.com/huggingface/tokenizers/blob/3aaf4946b3c82e7a04db6ecde7c8bb4e474e54af/bindings/python/py_src/tokenizers/implementations/byte_level_bpe.py#L18) (someone correct me if I'm wrong). This certainly complicates translating tiktoken to HF.

**Comment by colinclement** [comment]
I believe this issue is resolved, and in general the answer is "no" due to tiktoken supporting tokens as arbitrary byte arrays, not utf-8 byte sequences.

**Comment by hauntsaninja** [comment]
@mikcnt Sorry for the delay / I should have tested the snippet before posting it.

Here's a version that works. All you need to do is run a partial version of the BPE algorithm.
```
def bpe(mergeable_ranks: dict[bytes, int], token: bytes, max_rank: Optional[int] = None) -> list[bytes]:
    parts = [bytes([b]) for b in token]
    while True:
        min_idx = None
        min_rank = None
        for i, pair in enumerate(zip(parts[:-1], parts[1:])):
            rank = mergeable_ranks.get(pair[0] + pair[1])
            if rank is not None and (min_rank is None or rank < min_rank):
                min_idx = i
                min_rank = rank
        if min_rank is None or (max_rank is not None and min_rank >= max_rank):
            break
        assert min_idx is not None
        parts = parts[:min_idx] + [parts[min_idx] + parts[min_idx + 1]] + parts[min_idx + 2:]
    return parts

merges = {}
for token, rank in mergeable_ranks.items():
    if len(token) == 1:
        continue
    merges[token] = tuple(bpe(mergeable_ranks, token, max_rank=rank))
    assert len(merges[token]) == 2
```

@colinclement that's not correct. There is no assumption that tokens are valid UTF-8, even in HuggingFace code. It's impossible for BPE to work that way. They're using an encoding scheme to represent bytes as str, the same one from GPT-2:
https://github.com/openai/gpt-2/blob/a74da5d99abaaba920de8131d64da2862a8f213b/src/encoder.py#L9
https://github.com/openai/tiktoken/blob/46287bfa493f8ccca4d927386d7ea9cc20487525/tiktoken/load.py#L57
That's why you see the weird "Ġ" things; that character represents spaces.

tiktoken represents the bytes as bytes instead of weirdly encoded text because that's the straightforward thing to do: simple, fast, avoids confusion, avoids lossiness.

**Comment by colinclement** [comment]
@hauntsaninja I suppose I'm confused then about what Python strings are, because you can only make a Python `str` object from bytes if there is a valid encoding. If you try iterating over the gpt-2 tokens in tiktoken, many cannot be cast as Python str objects, and the Huggingface implementation does assume that the tokens themselves are Python str objects. So how can you use Huggingface with tokens of arbitrary byte sequences? Inserting the results of your code into Huggingface tokenizers fails because it only accepts `str` tokens and theres no consistent way to cast them as `str` (unless you roll your own, is that your point?). The funny G's are still valid unicode, you just have to have the second step in decoding of mapping them back down to standard whitespace.

**Comment by hauntsaninja** [comment]
See the links in my previous message to either the GPT-2 repo or tiktoken/load.py

**Comment by Jason3900** [comment]
> 

Thanks! Whereas the converted version is capable to deal with normal tokens, the whitespaces won't get merged which is different from tiktoken. eg. " " *2 will be tokenized as [220, 220] instead of [256]. Any idea to fix this?

**Comment by xenova** [comment]
@Jason3900 I think I've got the conversion working (just had to adapt @hauntsaninja's code slightly). Here's a link to it on HF: https://huggingface.co/Xenova/gpt-4

Example usage:
```py
from transformers import GPT2TokenizerFast

tokenizer = GPT2TokenizerFast.from_pretrained('Xenova/gpt-4')
assert tokenizer.encode('hello world') == [15339, 1917]
assert tokenizer.encode('  ') == [256]
```
(it will print a few warnings, because `GPT4Tokenizer` isn't officially supported, so I use `GPT2TokenizerFast` instead.

**Comment by leizhao1234** [comment]
> @mikcnt Sorry for the delay / I should have tested the snippet before posting it.
> 
> Here's a version that should work. All you need to do is run a partial version of the BPE algorithm.
> 
> ```
> def bpe(mergeable_ranks: dict[bytes, int], token: bytes, max_rank: Optional[int] = None) -> list[bytes]:
>     parts = [bytes([b]) for b in token]
>     while True:
>         min_idx = None
>         min_rank = None
>         for i, pair in enumerate(zip(parts[:-1], parts[1:])):
>             rank = mergeable_ranks.get(pair[0] + pair[1])
>             if rank is not None and (min_rank is None or rank < min_rank):
>                 min_idx = i
>                 min_rank = rank
>         if min_rank is None or (max_rank is not None and min_rank >= max_rank):
>             break
>         assert min_idx is not None
>         parts = parts[:min_idx] + [parts[min_idx] + parts[min_idx + 1]] + parts[min_idx + 2:]
>     return parts
> 
> merges = {}
> for token, rank in mergeable_ranks.items():
>     if len(token) == 1:
>         continue
>     merges[token] = tuple(bpe(mergeable_ranks, token, max_rank=rank))
>     assert len(merges[token]) == 2
> ```
> 
> @colinclement that's not correct. There is no assumption that tokens are valid UTF-8, even in HuggingFace code. It's impossible for BPE to work that way. They're using an encoding scheme to represent bytes as str, the same one from GPT-2: https://github.com/openai/gpt-2/blob/a74da5d99abaaba920de8131d64da2862a8f213b/src/encoder.py#L9
> 
> https://github.com/openai/tiktoken/blob/46287bfa493f8ccca4d927386d7ea9cc20487525/tiktoken/load.py#L57
> 
> 
> That's why you see the weird "Ġ" things; that character represents spaces.
> tiktoken represents the bytes as bytes instead of weirdly encoded text because that's the straightforward thing to do: simple, fast, avoids confusion, avoids mishandling.

@hauntsaninja @xenova , i use your code to convert a tiktoken tokenizer to hf, but i got an error.
`
token, rank  b'\xa0\xe9\x99\xa4' 23977
parts  [b'\xa0', b'\xe9', b'\x99', b'\xa4']
parts  [b'\xa0', b'\xe9\x99', b'\xa4']
merged  (b'\xa0', b'\xe9\x99', b'\xa4')
Traceback (most recent call last):
  File "/share/home/zl/convert/convert.py", line 9, in <module>
    convert_tiktoken(tik_token.tokenizer, "./hf_model")
  File "/share/home/zl/convert/tiktoken_to_hf/convert_utils.py", line 65, in convert_tiktoken
    vocab, merges = generate_vocab_and_merges(encoder)
  File "/share/home/zl/convert/tiktoken_to_hf/convert_utils.py", line 49, in generate_vocab_and_merges
    assert len(merged) == 2
AssertionError
`

**Comment by leizhao1234** [comment]
token, rank  b'\xa0\xe9\x99\xa4' 23977
parts  [b'\xa0', b'\xe9', b'\x99', b'\xa4']
parts  [b'\xa0', b'\xe9\x99', b'\xa4']
merged  (b'\xa0', b'\xe9\x99', b'\xa4')
Traceback (most recent call last):
  File "/share/home/zl/convert/convert.py", line 9, in <module>
    convert_tiktoken(tik_token.tokenizer, "./hf_model")
  File "/share/home/zl/convert/tiktoken_to_hf/convert_utils.py", line 65, in convert_tiktoken
    vocab, merges = generate_vocab_and_merges(encoder)
  File "/share/home/zl/convert/tiktoken_to_hf/convert_utils.py", line 49, in generate_vocab_and_merges
    assert len(merged) == 2
AssertionError

**Comment by zhaocc1106** [comment]
> token, rank b'\xa0\xe9\x99\xa4' 23977 parts [b'\xa0', b'\xe9', b'\x99', b'\xa4'] parts [b'\xa0', b'\xe9\x99', b'\xa4'] merged (b'\xa0', b'\xe9\x99', b'\xa4') Traceback (most recent call last): File "/share/home/zl/convert/convert.py", line 9, in <module> convert_tiktoken(tik_token.tokenizer, "./hf_model") File "/share/home/zl/convert/tiktoken_to_hf/convert_utils.py", line 65, in convert_tiktoken vocab, merges = generate_vocab_and_merges(encoder) File "/share/home/zl/convert/tiktoken_to_hf/convert_utils.py", line 49, in generate_vocab_and_merges assert len(merged) == 2 AssertionError

same issue

**Comment by alexstein0** [comment]
> @mikcnt Sorry for the delay / I should have tested the snippet before posting it.
> 
> Here's a version that should work. All you need to do is run a partial version of the BPE algorithm.
> 
> ```
> def bpe(mergeable_ranks: dict[bytes, int], token: bytes, max_rank: Optional[int] = None) -> list[bytes]:
>     parts = [bytes([b]) for b in token]
>     while True:
>         min_idx = None
>         min_rank = None
>         for i, pair in enumerate(zip(parts[:-1], parts[1:])):
>             rank = mergeable_ranks.get(pair[0] + pair[1])
>             if rank is not None and (min_rank is None or rank < min_rank):
>                 min_idx = i
>                 min_rank = rank
>         if min_rank is None or (max_rank is not None and min_rank >= max_rank):
>             break
>         assert min_idx is not None
>         parts = parts[:min_idx] + [parts[min_idx] + parts[min_idx + 1]] + parts[min_idx + 2:]
>     return parts
> 
> merges = {}
> for token, rank in mergeable_ranks.items():
>     if len(token) == 1:
>         continue
>     merges[token] = tuple(bpe(mergeable_ranks, token, max_rank=rank))
>     assert len(merges[token]) == 2
> ```
> 
> @colinclement that's not correct. There is no assumption that tokens are valid UTF-8, even in HuggingFace code. It's impossible for BPE to work that way. They're using an encoding scheme to represent bytes as str, the same one from GPT-2: https://github.com/openai/gpt-2/blob/a74da5d99abaaba920de8131d64da2862a8f213b/src/encoder.py#L9
> 
> https://github.com/openai/tiktoken/blob/46287bfa493f8ccca4d927386d7ea9cc20487525/tiktoken/load.py#L57
> 
> 
> That's why you see the weird "Ġ" things; that character represents spaces.
> tiktoken represents the bytes as bytes instead of weirdly encoded text because that's the straightforward thing to do: simple, fast, avoids confusion, avoids mishandling.

and @xenova to follow up on the question by @leizhao1234 and @zhaocc1106 about failing an assertion when `len(merges) != 2` I think the code provided is not sufficient to reverse the `mergeable_ranks` back into a merge tree.

As an example, I was attempting to take convert the LLama-3.2 `[tokenizer.model](https://huggingface.co/meta-llama/Llama-3.2-1B/blob/main/original/tokenizer.model)` into its `merges.txt` but it fails due to the order of the submerges in the partial `bpe`.

Here is an example:
When attempting to find the merges that produce the token `.:.:` the candidate pairs of subtokens [`.:`, `:.`, `.:`].  The one with the lowest is `:.`.  However this splits the original token into 3 instead of 2 (`. :. :`) which is what causes the assertion to fail.
I think what we would prefer to do is find all candidate *merges* rather than consecutive pairs (meaning [`. :.:`, `.: .:`, `.:. :` ]) and pick one of these as the merge that produced the original token `.:.:`.  The one we would want to pick is the one with the lowest id for the merge candidates.
