### ISSUE TITLE
Unable to find ENCODING_CONSTRUCTORS

### ISSUE THREAD

**Issue by dheerajiiitv** [openai/tiktoken#61]
This is happening when building tiktoken in bazel 
 
 enc = tiktoken.get_encoding(encoder)
  File "/private/var/tmp/_bazel_dheerajagrawal/795e110180f9443c94e6bab86cf49f84/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/metadata_extraction/functions/server/app.runfiles/__main__/utils/pypi/tiktoken_0.3.0/site-packages/tiktoken/registry.py", line 56, in get_encoding
    _find_constructors()
  File "/private/var/tmp/_bazel_dheerajagrawal/795e110180f9443c94e6bab86cf49f84/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/metadata_extraction/functions/server/app.runfiles/__main__/utils/pypi/tiktoken_0.3.0/site-packages/tiktoken/registry.py", line 36, in _find_constructors
    raise ValueError(
ValueError: tiktoken plugin tiktoken_ext.__pycache__ does not define ENCODING_CONSTRUCTORS

**Comment by hauntsaninja** [comment]
What's the best way for me to reproduce this error?

**Comment by dheerajiiitv** [comment]
Hi @hauntsaninja ,
I identified the issue, this issue is caused especially in Bazel and the reason the issue is coming is because of the creation of pycache module. 

Here you can see the outputs:

`
import importlib
import tiktoken_ext
import pkgutil

from pprint import pprint

if __name__ == "__main__":
    plugin_mods = pkgutil.iter_modules(tiktoken_ext.__path__, tiktoken_ext.__name__ + ".")

    for _, mod_name, _ in plugin_mods:
        mod = importlib.import_module(mod_name)
        try:
            constructors = mod.ENCODING_CONSTRUCTORS
            print(constructors)
        except Exception as e:
            print("Error", mod)
            pass`


Here's the output:

`Error <module 'tiktoken_ext.__pycache__' from '/private/var/tmp/_bazel_dheerajagrawal/795e110180f9443c94e6bab86cf49f84/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/text_extraction/functions/server/test_tiktoken.runfiles/__main__/utils/pypi/tiktoken_0.3.1/site-packages/tiktoken_ext/__pycache__/__init__.py'>
{'gpt2': <function gpt2 at 0x104b74dc0>, 'r50k_base': <function r50k_base at 0x106386670>, 'p50k_base': <function p50k_base at 0x106386700>, 'p50k_edit': <function p50k_edit at 0x106386790>, 'cl100k_base': <function cl100k_base at 0x106386820>}`

**Comment by rishabh-sagar-20** [comment]
Any update on this @hauntsaninja?

**Comment by flying-sheep** [comment]
The problem is not that `__pycache__` exists, that’s normal. The problem is that `pkgutil.iter_modules` isn’t smart enough to skip it. So you should skip it yourself instead.

**Comment by dheerajiiitv** [comment]
@flying-sheep please make them merge it.
