### ISSUE TITLE
String concatenation / insertion and BPE length

### ISSUE THREAD

**Issue by adri1wald** [openai/tiktoken#70]
Given any strings `s1` and `s2`, with corresponding BPE lengths `l1` and `l2`:
1. Is it always the case that the concat of `s1` and `s2` has a BPE length `<= l1 + l2`?
2. What about an arbitrary insertion of `s2` into `s1`?

I feel like the answer to 1 is yes and the answer to 2 is no.

Right now I add a bit of "leeway" in code that checks and limits context length. Here's a scenario where this is important:

Prompt
```plaintext
Some prefix stuff...
{variable_input}
Some suffix stuff...
```

I first get the `excess_tokens`:
```py
excess_tokens = prompt_tokens + max_completion_tokens - max_model_tokens + leeway
```

If it's `<= 0` all is good and we can send the request.
If it's `> 0` then I need to truncate `variable_input` in some fashion.

To get the max tokens for `variable_input`:
```py
max_variable_input_tokens = variable_input_tokens - excess_tokens
```

I then truncate `variable_input` in some usecase-specific way, reformat the prompt with the truncated version, and send it on its merry way.

I'd like to assume `leeway = 0` will always work, but right now I am not confident this is a valid assumption, so I've set it to `10`. In the grand scheme of things it doesn't really make a difference, but I'm curious about the concrete answer.

**Comment by hauntsaninja** [comment]
The answer to the first question is no, so the answer to the second question is no.
```
>>> import tiktoken
>>> enc = tiktoken.get_encoding("gpt2")
>>> enc.encode(" wearable")
[39092]
>>> enc.encode("direct")
[12942]
>>> enc.encode(" wearabledirect")
[5806, 4510, 1060]
```
And no, one isn't sufficient either. 10 seems somewhat safe in practice.
