### ISSUE TITLE
Counting tokens from messages (GPT-4)

### ISSUE THREAD

**Issue by OTheDev** [openai/tiktoken#71]
The OpenAI Cookbook includes a [recipe](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) for counting the number of tokens in a list of messages if the model is `"gpt-3.5-turbo-0301"`.

From previously closed issues on the GPT-4 subject, it looks like the same encoding of `"cl100k_base"` is used. Experimenting with a few API calls, I've noticed that `"gpt-4"` tends to report 1 less token for the prompt than that returned from a completion given by `"gpt-3.5-turbo"` or pre-calculated using the linked recipe.

Is this documented somewhere?

**EDIT**: Apologies, I should clarify that the observations above are for one message (one element list) prompts consisting of values for `"role"` and `"content"`.

**Comment by ted-at-openai** [comment]
Thanks for catching. We just changed how we count tokens on our backend. Total token consumption is the same, but we're now counting one more token as part of the prompt and one less for the completion. I'll update the code. Be aware that this may change again in the future.
