### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by realliyifei** [openai/tiktoken#75]
I cannot use tiktoken in python:

Input `encoding = tiktoken.get_encoding('cl100k_base')`,

it gives the error `PermissionError: [Errno 13] Permission denied: '/tmp/data-gym-cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4.2749b823-646b-45d7-9fcf-11414469d900.tmp'`

But I can use it in my colab.

**Comment by hauntsaninja** [comment]
Try setting the environment variable `TIKTOKEN_CACHE_DIR=""`

**Comment by balajivenkatesh** [comment]
Is there another way to fix the same issue? I do not have access to set an environment variable.

**Comment by subhojit-me** [comment]
getting the same issue when deployed a django application with langchain package in IIS using HttpPlatformModule, can anyone let me know how to resolve this?

**Comment by alexanderreschjedox** [comment]
If you are using this in a kubernetes environment, you can do the following:

1. make an environment variable for tiktoken
TIKTOKEN_CACHE_DIR = "desired_path_to_tmp"

2. Add the directory to your dockerfile and make the user owner of that directory
RUN mkdir /desired_path_to_tmp && chown -R 2:2 /desired_path_to_tmp

**Comment by wookayin** [comment]
You will get this error in a multi-user system. When some other users have already created the cache dir `/tmp/data-gym-cache`, they own the directory, and you don't have the permission. It's a bad idea to hard-code the temporary directory.

**Comment by hauntsaninja** [comment]
I've pushed a change that will swallow the PermissionError in the default case. This will be released in tiktoken 0.5.2
