### ISSUE TITLE
Utilize trained huggingface tokenizer with tiktoken

### ISSUE THREAD

**Issue by kbmmoran** [openai/tiktoken#78]
Hello, we have a trained roberta tokenizer which through using Huggingface. Is it possible to utilize this tokenizer with tiktoken? From your code, it seems we could pass an vocab.bpe and encoder.json file, however, the vocab files for roberta tokenizers seem to differ from the BPE files. As they are not only json files, but the main difference seems to be the spaces between some of the characters in the vocab.bpe file.

Is this something that is doable?

**Comment by hauntsaninja** [comment]
I'm not familiar with the specifics of what file format HuggingFace is using for Roberta tokenizers.

Note that the loading code is only a convenience and isn't baked into `tiktoken` in any way. The Encoding object just takes a dictionary of bytes to tokens: https://github.com/openai/tiktoken/blob/46287bfa493f8ccca4d927386d7ea9cc20487525/tiktoken/core.py#L18 
The encoding registry mechanism just creates kwargs for the Encoding class however you feel like:
https://github.com/openai/tiktoken/blob/46287bfa493f8ccca4d927386d7ea9cc20487525/tiktoken_ext/openai_public.py#L28
https://github.com/openai/tiktoken/tree/main#extending-tiktoken
