### ISSUE TITLE
Include py.typed file so type checkers work

### ISSUE THREAD

**Issue by rshin** [openai/tiktoken#8]
[PEP 561](https://peps.python.org/pep-0561/) requires that a `py.typed` file be present at the root of a package to indicate that the package supports typing:

- https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/
- https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

**Comment by hauntsaninja** [comment]
Thanks for mentioning. I've addressed this in [tiktoken 0.1.2](https://github.com/openai/tiktoken/blob/main/CHANGELOG.md#v012). Let me know if you have further issues!
