### ISSUE TITLE
ValueError: Unknown encoding cl100k_base

### ISSUE THREAD

**Issue by rembo1992** [openai/tiktoken#80]
When I am running the python code below in pyCharm or Replit it is running fine. But after I create an executable with pyInstaller I am getting the following error in the console when running the exe file:

Traceback (most recent call last):
File "main.py", line 74, in count_tokens
File "tiktoken\registery.py", line 60
ValueError: Unknown encoding cl100k_base'

What is causing this strange issue?

Below you can see the tiktoken 'count_tokens' function with a sample of 'message_storage_str'.
The line 74 is referring to  'try:'

`import tiktoken #0.3.2

messages_storage_str = 'orem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vulputate euismod pharetra. Pellentesque non turpis ut turpis rhoncus malesuada rhoncus sed erat. Maecenas mi nulla, dignissim et justo quis, egestas ultricies risus.'

try:
    encoding = tiktoken.encoding_for_model("gpt-3.5-turbo")
except KeyError:
    encoding = tiktoken.get_encoding("cl100k_base")
tokens_list = encoding.encode(messages_storage_str)  # bijv. [83, 1609, 5963, 374, 2294, 0]
tokens_total = len(tokens_list)  # bijv. 100
print(tokens_total)  # totaal aantal tokens (excl. openai response bericht)`

**Comment by rembo1992** [comment]
I found the fix for the problem for the tiktoken\registery 'ValueError: Unknown encoding'.

Add the following to your pyinstaller prompt to make it executable:

`--hidden-import=tiktoken_ext.openai_public --hidden-import=tiktoken_ext`

**Comment by moonlburger** [comment]
Worked like a charm. Thank you, this had me stumped.

**Comment by averypfeiffer** [comment]
Great! This solved my problem as well, but i'd like to understand why it was needed, in case I run into something like this again.

**Comment by christopherquenneville** [comment]
> I found the fix for the problem for the tiktoken\registery 'ValueError: Unknown encoding'.
> 
> Add the following to your pyinstaller prompt to make it executable:
> 
> `--hidden-import=tiktoken_ext.openai_public --hidden-import=tiktoken_ext`

Thanks a lot

**Comment by yjg30737** [comment]
Thanks rembo ! You're dude of the month.

**Comment by zndqs** [comment]
> Great! This solved my problem as well, but i'd like to understand why it was needed, in case I run into something like this again.

it seems happend when use "importlib.import_module(xxx)" ,PyInstaller didn`t know the "xxx" is involved

**Comment by AnujKshatriya** [comment]
Thanks, it really worked !!
