### ISSUE TITLE
Encoding french document

### ISSUE THREAD

**Issue by christopher5106** [openai/tiktoken#82]
From a PDF document from which I extract the text with PyPDF, I get the following error on a char, what should I do ?

```
import tiktoken
enc = tiktoken.get_encoding("gpt2")
 enc.encode('\udbc0')
```

Leading the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/User/Desktop/systra_qa/venv/lib/python3.8/site-packages/tiktoken/core.py", line 99, in encode
    return self._core_bpe.encode(text, allowed_special)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udbc0' in position 0: surrogates not allowed

**Comment by hauntsaninja** [comment]
I have a patch internally that makes this not an error, but note that a lone surrogate is meaningless. The patch I have will treat a lone surrogate like "�".

**Comment by christopher5106** [comment]
I was wondering if you encountered this kind of chars during training, and what normalization you used, to be sure not to have a loss. 
There are many other situations as this one, dealt by this lib for example: https://ftfy.readthedocs.io/en/latest/

**Comment by hauntsaninja** [comment]
I released 0.3.3 which changes tiktoken to try and replace surrogate code pairs with the appropriate codepoint and replaces lone surrogate with the unicode replacement char: https://github.com/openai/tiktoken/blob/main/CHANGELOG.md#v033

I don't know that we've talked publicly about what preprocessing we do when training, but you're welcome to play with our models and see if you can figure out what's in and out of distribution :-) For the specific case of surrogate pairs, I think it's relatively hard to end up with them if you manage encodings correctly.

**Comment by christopher5106** [comment]
Thanks 👍

**Comment by christopher5106** [comment]
Just a question: when we submit text to openai servers, how does it deal with such errors ? Is it the same tokenizer ?
