### ISSUE TITLE
Estimate total_tokens

### ISSUE THREAD

**Issue by loretoparisi** [openai/tiktoken#84]
Hello, when in ChatML mode (chatCompletion api) I get a variable number of `completion_tokens`
depending on the input and output that I cannot estimate.
While I can estimate correctly `prompt_tokens`
using tiktoken for both DaVinci and ChatGPT Turbo, I'm not aware of a way to estimate the `total_token` after the api call that will be used for billing.
Is there any way to do that?

```
{
usage: { 
          prompt_tokens: 1740,
          completion_tokens: 256, 
total_tokens: 1996  
     },
}
```

In the provided example, I correctly get `prompt_tokens` using tiktokenizer. My guess is that `completion_tokens` are a diff of the input tokens dictionary and the output dictionary, so that the total tokens will be a Set of both input (prompt) tokens and output (completion) tokens, therefore without repetitions.
Is this assumption correct?

**Comment by hauntsaninja** [comment]
The chat endpoint lets you specify a max_tokens number to limit the number of tokens generated: https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens

You could also try modifying your prompt to ensure relatively consistent lengths.

Overall, this isn't really the right forum for this kind of question. Consider contacting support@openai.com if you need more help!
