### ISSUE TITLE
Inconsistency in number of tokens

### ISSUE THREAD

**Issue by ahmed-mohamed-sn** [openai/tiktoken#85]
I am trying to use OpenAI embeddings to get the embeddings of a big collection of data (4M+) to make sure that the run isn't interrupted, I filtered out the data with more than 8191 tokens and used the following code to calculate the number of tokens.

```
  tiktoken_encoder = tiktoken.encoding_for_model("text-embedding-ada-002")
  text_tokens = tiktoken_encoder.encode(text)
  return len(text_tokens)
```

I still got errors that I exceeded the max number of tokens (this cost me over $400 already):

`This model's maximum context length is 8191 tokens, however, you requested 8469 tokens (8469 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.`

**Comment by hauntsaninja** [comment]
I checked text-embedding-ada-002 and it's working correctly for me. That is:
`openai.Embedding.create(input=enc.decode(enc.encode(long_text)[:8191]), model="text-embedding-ada-002")["data"][0]["embedding"]` works but `openai.Embedding.create(input=enc.decode(enc.encode(long_text)[:8193]), model="text-embedding-ada-002")["data"][0]["embedding"]` fails

Try:
- Using the code from https://github.com/openai/openai-cookbook/blob/main/examples/Embedding_long_inputs.ipynb 
- Double checking you're using the right model
- Contacting support@openai.com
