### ISSUE TITLE
License for tokenizer models are unclear

### ISSUE THREAD

**Issue by VRandme** [openai/tiktoken#92]
Although the tiktoken tokeniser library itself is clearly presented as being licensed as the MIT license,
The license for the tokeniser encodings such as  "gpt2",  "r50k_base", "p50k_base", "p50k_edit" or "cl100k_base" are unclear.
This is particulary problematic since they are not part of this repo but hosted on external links 
ex) "https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken"
This adds to the ambiguity.

Please state the license(or lack thereof) and (if applicable) the ToS of such encodings.

**Comment by hauntsaninja** [comment]
The license in this repo applies to the encoding files as well. Thanks!

**Comment by yole** [comment]
Would it be possible to state that in the LICENSE file, or somewhere else which is not a GitHub issue? Thanks!
