### ISSUE TITLE
Add support for Pyodide

### ISSUE THREAD

**Issue by Emasoft** [openai/tiktoken#94]
Please add support for [Pyodide](https://github.com/pyodide/pyodide).
Pyodide was created in 2018 by [Michael Droettboom](https://github.com/mdboom) at Mozilla as part of the [Iodide project](https://github.com/iodide-project/iodide). Iodide is a web-based notebook environment for literate scientific computing and communication.

Pyodide is a Python distribution for the browser and Node.js based on WebAssembly.

## What is Pyodide?

Pyodide is a port of CPython to WebAssembly/[Emscripten](https://emscripten.org/).

Pyodide makes it possible to install and run Python packages in the browser with
[micropip](https://pyodide.org/en/stable/usage/api/micropip-api.html). Any pure
Python package with a wheel available on PyPi is supported. Many packages with C
extensions have also been ported for use with Pyodide. These include many
general-purpose packages such as regex, PyYAML, lxml and scientific Python
packages including NumPy, pandas, SciPy, Matplotlib, and scikit-learn.

Pyodide comes with a robust Javascript ⟺ Python foreign function interface so
that you can freely mix these two languages in your code with minimal friction.
This includes full support for error handling, async/await, and much more.

When used inside a browser, Python has full access to the Web APIs.

## Try Pyodide (no installation needed)

Try Pyodide in a
[REPL](https://pyodide.org/en/stable/console.html) directly in
your browser. For further information, see the
[documentation](https://pyodide.org/en/stable/).

## Example Projects running in Pyodide
[Pydantic-core](https://github.com/pydantic/pydantic-core)
[Pydantic-core running in browser](https://githubproxy.samuelcolvin.workers.dev/pydantic/pydantic-core/blob/main/wasm-preview/index.html)

**Comment by hauntsaninja** [comment]
Thanks, I'm not currently planning on providing Pyodide wheels. I've linked to this issue in the FAQ https://github.com/openai/tiktoken/issues/98 ; if this proves to be a popular request, I'll reopen

**Comment by MRYingLEE** [comment]
+1

**Comment by psymbio** [comment]
I think the issue has enough support (https://github.com/openai/tiktoken/issues/98) to be taken up again.

See:
https://github.com/openai/tiktoken/issues/57
https://github.com/openai/tiktoken/issues/134
https://github.com/josephrocca/gpt-2-3-tokenizer/issues/2
https://github.com/pyodide/pyodide/issues/3875
https://github.com/pyodide/pyodide/issues/3663
https://github.com/pyodide/pyodide/issues/3543
https://github.com/emscripten-forge/recipes/issues/660

A pure Python version need not be created just some patches for the wasm for Pyodide. I have worked on the script for creating the wasm wheel https://github.com/psymbio/tiktoken_rust_wasm/ (the README describes the steps) and for testing use this [wheel](https://github.com/psymbio/tiktoken_rust_wasm/blob/main/packages/build_emscripten/tiktoken-0.5.1-cp311-cp311-emscripten_3_1_45_wasm32.whl), usage in [index.html](https://github.com/psymbio/tiktoken_rust_wasm/blob/main/index.html) and view the error on console.

**Comment by Emasoft** [comment]
There are already 2 pure python implementations of the tokenizer: 

In the educational version:
https://github.com/openai/tiktoken/blob/main/tiktoken/_educational.py
In this fork, courtesy of [@kechan](https://github.com/kechan):
https://github.com/kechan/tiktoken
As discussed here: https://github.com/openai/tiktoken/issues/36

@hauntsaninja  Since everything is in place, when are you going to add the Pyodide compatible version of Tiktoken? We really need it.

**Comment by psymbio** [comment]
It's not fully completed [gpt2 isn't completed; gpt4, cl100k_base, p50k, and r50k completed](https://github.com/psymbio/tiktoken/blob/cached_weights/tiktoken_ext/openai_public.py) will look into this probably by this week. The compilation is pretty time-consuming and is documented [here](https://github.com/psymbio/tiktoken_rust_wasm/blob/main/README.md) (will need to clean this up as well).

But for the time-being you can use the following:
```python
import micropip
await micropip.install("https://raw.githubusercontent.com/psymbio/pyodide_wheels/main/tiktoken/tiktoken-0.5.1-cp311-cp311-emscripten_3_1_45_wasm32.whl", keep_going=True)
import tiktoken
enc = tiktoken.get_encoding("cl100k_base")
assert enc.decode(enc.encode("hello world")) == "hello world"
enc = tiktoken.encoding_for_model("gpt-4")
assert enc.decode(enc.encode("hello world")) == "hello world"
```

@hauntsaninja can you look at the feasibility of a PR here?

**Comment by maartenbreddels** [comment]
I compiled version 0.7 for wasm/pyodide, and put it at https://py.cafe/maartenbreddels/tiktoken-demo

Note that you can right-click the file in the file browser, copy the public URL to your clipboard, and use it in other projects for your requirements.txt.

At pycafe you don't have CORS issues, so we did not use the trick from @psymbio for version 0.7 (0.5 is similar to his)
